<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Rekordowe nurkowanie w Ciasnych Kominach
</h1>

<p>Jaskinia Miętusia - jedna  z  największych  w  Polsce  -  już  od najwcześniejszych etapów eksploracji  była  arena  rozwoju  nurkowania podziemnego w naszym kraju. W 1957 grupa płetwonurków związanych z Marynarka Wojenna pokonała przy  użyciu  aparatów   tlenowych   ISAM-48   syfon   powyżej   Progu Męczenników. Stad nosi on dzisiaj nazwę Marwoj. Na  początku  lat  siedemdziesiątych nurkowie ze Speleoklubu Warszawskiego prowadzili eksplorację w syfonie na dnie Wielkich Kominów - już przy użyciu aparatów powietrznych. Na głębokości -28m dotarli do rozwidlenia korytarza (kolektor). Jednak na skutek  zatrucia  tlenkiem węgla ostatnia akcja została przerwana. W poźniejszych latach spadło zainteresowanie nurkowaniem w tej jaskini. Wynikało to po części z dosyć uciążliwego transportu (Rura), w porównaniu z takimi jaskiniami jak Kasprowa Niżnia  czy  Bystra,  oraz braku perspektyw na spektakularne pogłębienie jaskini, jak w  Wielkiej Śnieżnej czy Śnieżnej Studni.</p>
<p>Dopiero na początku lat 90-tych odbyły się kolejne nurkowania. K. Starnawski ponownie doszedł  do  kolektora  w  Wielkich  Kominach.  I. Szymczak i T. Witkowski zanurzyli  się  po  raz  pierwszy  w  Ciasnych Kominach. Zeszli na głębokość -15m, gdzie  natknęli  się  na  obszerny poziomy korytarz.</p>
<p>Ocena atrakcyjności poszczególnych syfonów ulęgła przewartościowaniu po  nawiązaniu  przez  nasze  środowisko  kontaktów międzynarodowych  (a  zwłaszcza  z  Francuzami).   Okazało   się,   że penetracja zalanych korytarzy może być celem  samym  w  sobie,  a  nie tylko pokonywaniem bariery wodnej, w celu znalezienia  dalszego  ciągu suchych korytarzy czy też pogłębienia jaskini.</p>
<p>Na początku lutego sporo  ludzi  z  Wrocławia  zdradzało  chęć  do wzięcia  udziału  w  weekendowej  akcji.  W  ten  sposób   udało   się zorganizować nurkowanie w Jaskini Miętusiej. Wzięli w  niej  udział  : Wiktor Bolek - kierownik, płetwonurek, E. Iwanski (Głogów), G.  Kaczor (Głogów), M. Mieszkowski, M. Stajszczyk - wszyscy SG KW  Wrocław  oraz J. Bińczak, M. Jankowiak i A. Leśniewska z SCW.. Do jaskini  weszliśmy 03 lutego  o  godz.  11.  Pod  otworem  spotkaliśmy  się  z  Krzyśkiem Starnawskim, który od dłuższego czasu przygotowywał się do  nurkowania w Wielkich Kominach. Aby  nie  wchodzić  sobie  w  drogę  postanowiłem zmienić plany i zanurkować jednak w Ciasnych Kominach.</p>
<p>Szybko okazało się, że te ciasności  nie  są  wcale  iluzoryczne. Polowa ekipy przestraszyła się trudności i nie przeszła  przez  Zacisk Kaczanosia nie mówiąc już o Drodze Przez Mękę. Akcja doszła do  skutku w zasadzie tylko dzięki mężnej  postawie  kolegów  z  Głogowa.  Dalsza droga do syfonu też obfitowała w przygody. Maciek z SCW  nie  odnalazł właściwego wejścia do Zacisku Ucho Igielne i obszedł  go  nurkując  na bezdechu w kałuży. Nie obniżyło to wcale jego sprawności, a  poza  tym nie bardzo chwalił się swoim wyczynem, tak że szczegóły udało się  nam ustalić dopiero po powrocie na bazę.</p>
<p>Nurkowanie rozpoczęliśmy po ok. 6 godz. od  wejścia  do  jaskini. Skalna  półka  nad  lustrem  wody  była  bardzo  niewygodna.   Znaczna pochyłość powodowała, ze drobny sprzęt od  czasu  do  czasu  znikał  w błękitnej otchłani syfonu. Już podczas składania sprzętu okazało  się, ze jedna z ośmiolitrowych butli jest pusta. W zasadzie w tym  momencie powinienem był  zakończyć  akcje,  gdyż  ze  względów  bezpieczeństwa wymaga się dwu niezależnych  zestawów.  A  mnie  została  tylko  jedna butla.  Żeby  jednak  cały  włożony  wysiłek  nie  poszedł  na   marne postanowiłem  podjąć  ryzyko  i  zanurzyć  się.  Wszedłem  do  prawego orograficznie oczka syfonu, gdyż tu akurat  zejście  było  łatwiejsze. Szymczak i Witkowski nurkowali ponoć w lewym.</p>
<p>Woda  była  początkowo  zmącona  w  wyniku  szamotaniny podczas zakładania sprzętu na płytkiej wodzie. Zanurzałem się powoli. Musiałem pokonywać dodatnia pływalność odpychając się od ścian.  Na  głębokości 2-3 metry kończyła się stroma półeczka i zacząłem opadać w dół pionowa studzienką.  Widoczność  poprawiła  się  do  kilkunastu   metrów.   Na głębokości  11m  zobaczyłem  obszerny,  regularny  korytarz  idący  na północ. Miał średnicę 4 do 5  metrów.  Nieco  po  lewej  była  pionowa szczelina o wysokości ok. 3 m i szerokości 1m.  Wyglądało  na  to,  ze kończy się po kilkunastu metrach. Zapewne jest to połączenie  z  lewym jeziorkiem. Innych połączeń nie dostrzegłem.  Za  mną  woda  była  już zmącona i widoczność ograniczała  się  do  1  metra.  Zastabilizowałem poręczowkę  zaczepiając  gumkę  o  bardzo   wygodny   występ   skalny. Postanowiłem popłynąć głównym korytarzem. Łagodnie opadał w dół. Przez cały czas był jednakowo przestronny. Widoczność doskonała. Czułem  się jak  podczas  nurkowań  we  Francji  w  Ressel.  Próbowałem   zauważyć dochodzący z góry  ciąg,  który  mógłby  być  połączeniem  z  Wielkimi Kominami. Nic takiego  jednak  nie  dostrzegłem.  Dno  korytarza  było pokryte gruboziarnistym piaskiem. Ponieważ płynąłem pod stropem,  woda nie mąciła się zbytnio.  Spojrzałem  na  komputer  -  byłem  na  -30m. Bardzo łatwo zdobywało się tutaj głębokość. Postanowiłem zejść jeszcze na  -  35m.  Całkowicie  zaufałem  swojemu  automatowi  Scubapro,   że przetrwał transport i nie ulegnie awarii w  krytycznym  momencie.  Nie mogłem przecież skorzystać z  Poseidona  na  drugiej  butli.  Chwilowo zawieruszył mi się gdzieś manometr i nie wiedziałem  ile  jeszcze  mam powietrza. Ale na komputerze odczytałem  już  35.6  m.  Na  poręczówce minąłem właśnie marker z napisem 60m. Zatrzymałem się. Minęło 6 minut od zanurzenia. Zawiązałem kluczkę i zastabilizowałem poręczówkę za pomocą ciężarka. Odciąłem linkę z kołowrotka sekatorkiem i rozpocząłem powrót. Widoczność zmalała do 1 metra. Bardzo powoli  mijałem  kolejne markery : 55m, 50m,..., 40m. Dalej nie mogłem  odnaleźć  manometru.  W pewnej chwili stwiedziłem, ze zbyt mocno  pracuje  nogami.  Uspokoiłem ruchy, by  nie  dostać  zadyszki.  Odetchnąłem  z  ulga  dopiero,  gdy dopłynąłem do gumki na -11. Stad już mogłem wynurzyć się  bezpośrednio na powierzchnie. W tym momencie manometr sam się odnalazł. Zostało  mi jeszcze 60 atm., czyli zużyłem 2/3 powietrza na penetracje - zgodnie z podręcznikiem. Upływała trzynasta minuta nurkowania. Powoli wychodziłem na  powierzchnię. Co prawda  komputer   nie   pokazywał konieczności  wykonania  dekompresji,  ale chciałem zwiększyć  swój margines bezpieczeństwa. Po kilku minutach znów zacząłem  oddychać normalnym powietrzem.</p>
<p>Podczas powrotu najbardziej dało mi się we znaki  wyjście  studni do miejsca, gdzie przebierałem  się.  Musiałem  to  wykonać  na  samej poignee, bo uprząż  nie  wchodziła  na  pianekę.  Wykonywanie  zwinnych ruchów było bardzo  utrudnione,  gdyż  za  każdym  razem  trzeba  było wydatkować jeszcze sporo energii na rozciąganie neoprenu kilkumilimetrowej  grubości. Po przebraniu i przełknięciu kilku ciepłych kęsów, retransport poszedł nadspodziewanie łatwo. Całą akcję zakończyliśmy po 16 godzinach.</p>
<p>Było to jedno z najpiękniejszych nurkowań w mojej karierze, a  na pewno najgłębsze z wykonanych dotychczas w naszym kraju.  Przestronne, głębokie korytarze, woda co  prawda  mąci  się,  ale  nie  tragicznie. Podwodny kolektor dalej mknie na dół nie zmieniając  gabarytów.  Gdyby nie  przejście  przez  Ciasne  Kominy,  byłoby  to  najatrakcyjniejsze miejsce do uprawiania podwodnej speleologii.</p>


<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>