<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Retransport sprzętu
</h1>

<p>W styczniu 98 przeprowadziliśmy akcję nurkową w Ciasnych Kominach w Jaskini Miętusiej. Podczas nurkowania trimixowego w południowym jeziorku osiągnąłem głębokość 63m. W północnym jeziorku nurkował Norbert Ziober, który osiągnął 13m w jednym kierunku, a w drugą stronę korytarz wznosił się dając nadzieję na wynurzenie.</p>
<p>Po udanej akcji pozostawało już "tylko" wynieść sprzęt - w sumie sześć butli i parę innych "drobiazgów". W połowie lutego była odpowiednia ilość chętnych do transportu. Jednak tym razem pogoda zniweczyła nasze zamierzenia. Podczas trzech dni intensywnych opadów deszczu nie wyszliśmy nawet z bazy. Taki rozwój wypadków mocno nas zdeprymował. Zima miała się końcowi i Syfon Zwolińskich będzie zalany najprawdopodobniej aż do listopada bądź grudnia. Sprzęt pozostawiony w jaskini był do odzyskania tylko przy każdorazowym nurkowaniu w połowie jaskini. Jest to dosyć koszmarna perspektywa, zważywszy, że nie ma w naszym kraju zbyt wielu osób, które byłyby w stanie uczestniczyć w  trudnej akcji jaskiniowej po nurkowaniu.</p>
<p>Nie mając jednak innego wyjścia, chodziliśmy we dwóch z Norbertem na retransporty. Na jeden z wyjazdów udało się nam namówić jeszcze Maćka Czykierdę na przenurkowanie Syfonu Zwolińskich. Do jaskini wnieśliśmy dwie dodatkowe butle i sprzęt potrzebny do przepłynięcia zalanego odcinka. Nie byliśmy już w stanie wnieść dodatkowych pasów balastowych. Znacznie utrudniło to przepływanie syfonu. Ponieważ było nas trzech - jeden z nas musiał przepłynąć na bezdechu. Ponieważ najlepiej znałem topografię tego miejsca zdecydowałem się na wykonanie tego manewru. Mając dodatnią pływalność, położyłem się na plecach z twarzą przy stropie, żeby móc jak najdłużej oddychać. Strop był z litej skały, w którym woda wyrzeźbiła niegdyś liczne wgłębienia. Strop powoli zbliżał się do lustra wody. Wkładałem nerwowo wargi w kolejne wgłębienia by jeszcze raz wziąć oddech, po czym zanurzyłem się. W krystalicznie czystej wodzie przed sobą zobaczyłem długi zalany odcinek. Miał chyba 2 m. Spodziewałem się, że będzie to co najwyżej kilkadziesiąt centymetrów. Że wystarczy w zasadzie przełożyć głowę na drugą stronę. Podciągnąłem się szybko na zostawionej tu poprzednim razem linie i wynurzyłem się po drugiej stronie. Mimo wszystko pokonywanie każdego zalanego odcinka na bezdechu w jaskini wiąże się z olbrzymim stresem. Na szczęście w drodze powrotnej będziemy mogli wykorzystać butle wyniesione z Ciasnych Kominów i taki manewr nie będzie już konieczny. W Sali Bez Stropu zostawiliśmy sprzęt nurkowy i poszliśmy dalej. Wody było dużo. Najbardziej przykra była studnia nad Kaczanosiem, gdzie całym przekrojem lał się obfity deszcz.</p>
<p>Gdy dotarliśmy na dno Ciasnych Kominów, okazało się, że w dwu ósemkach jest jeszcze po 100 bar.  Norbert, który przewidująco wziął ze sobą suchy kombinezon, ponownie zanurkował w północnym jeziorku. Tym razem komfort nurkowania miał znacznie większy ze względu na krystalicznie czystą wodę. W dużym oknie, gdzie poręczówka przechodziła do równoległego korytarza, dowiązał linkę z nowego kołowrotka i popłynął dalej na północ. Znalazł się w obszernej sali, z której w kierunku południowych wychodziły trzy korytarze. Pierwszym z nich przypłynął, drugi wyeksplorował poprzednim razem do -13m. Natomiast trzeciego korytarza nie zauważył, ze względu na zmącenie wody. Popłynął jednak najpierw na północ do miejsca, gdzie, jak wynikało z poprzedniej akcji, istniała możliwość wynurzenia się na powierzchnię. Jednak na głębokości -5m sala przechodziła w wąską, ukośną szczelinę o szerokości 1m, która dalej biegła w górę. Ponieważ nie był przygotowany psychicznie na przeciskanie się pod wodą, odpuścił na razie ten problem i popłynął do trzeciego korytarza. Była to opadająca w dół pochylnia. Po kilkunastu metrach drugi i trzeci korytarz łączyły się. Dalej na głębokości -20m, pochylnia zakręcała pod kątem 900 na południe. W tym miejscu był bardzo charakterystyczny fragment skały, który otrzymał nazwę Maczuga. Do niej właśnie Norbert zastabilizował kończącą się poręczówkę. Podczas powrotu wyciągnął jeszcze z drugiego korytarza zostawioną poprzednio poręczówkę z kołowrotkiem.</p>
<p>Po nurkowaniu spakowaliśmy sprzęt i rozpoczęliśmy retransport. Podczas wychodzenia najbardziej wyczerpujące było pokonanie studni nad Kaczanosiem, gdzie do szpejów (worki transportowe) dostało się dużo wody, przez co ważyły chyba po 20 kilo. Co gorsza okazało się, że koszulka liny jest w wielu miejscach uszkodzona od intensywnie padającej wody. Po ponownym przenurkowaniu Syfonu Zwolińskich byliśmy na tyle zmęczenie, że porzuciliśmy wszystko w meandrze przed Komorą z Matką Boską i Rurę wyszliśmy na lekko. Szpeje wynieśliśmy dopiero następnego dnia po odespaniu 18 godzinnej akcji.</p>
<p>Kampania zimowa 97/98 w Ciasnych Kominach była bardzo ciężka. Głównym powodem była fatalna pogoda, która uniemożliwiała wzięcie udziału w transporcie większej liczbie osób. Doniesienie wszystkiego na miejsce wymagało wielokrotnych, kosztownych wyjazdów do Zakopanego. Mimo to udało się ostatecznie uzyskać dobre rezultaty. W południowym jeziorku wykonano pierwsze w Polsce nurkowanie na trimixie w jaskini, ustanawiając nowy rekord głębokości na -63.1m. Odkryto przy tym 25m nowego, przy czym korytarz kontynuuje się dalej w dół. Po raz pierwszy przeprowadzono eksplorację w północnym jeziorku, odkrywając dwa nowe przodki. W jednym z nich zapewne będzie możliwość wynurzenia się na powierzchnię, drugi daje podobne perspektywy na osiągnięcie dużych głębokości jak w południowym jeziorku. Odkryto tu w sumie korytarze o długości około 80m. Przeprowadzono akcję z nurkowaniem za zalanym Syfonem Zwolińskich. Stwarza to umożliwić prowadzenia eksploracji również latem. Jednak warunkiem jest zaangażowanie większej liczby osób będących w stanie uczestniczyć w akcji jaskiniowej po drugiej stronie syfonu.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>