<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Ciasne Kominy po raz drugi
</h1>

<p>Podczas poprzedniego nurkowania uległem fascynacji syfonem na dnie Ciasnych Kominów w Jaskini Miętusiej. Ogromne przestrzenie, klarowna woda, korytarz wiodący w nieznane. Jednak napotkane trudności były wcale niebagatelne. Fakt, że Ciasne Kominy są jednym z najrzadziej odwiedzanych miejsc w tej jaskini, mówi sam za siebie. W naszym klubie niewielu jest grotołazów, którzy mieli odwagę zmierzyć się z Kaczanosiem, Wyżymaczką, Drogą Przez Mękę, Uchem Igielnym. Za pierwszym razem tylko połowa ekipy ujrzała lustro wody w syfonie. Miałem nadzieję, że następnym razem pójdzie lepiej.</p>
<p>Pod koniec grudnia 1996 nastały silne mrozy, co pozwalało przypuszczać, że jaskinia będzie łatwo dostępna. Szybka zorganizowałem ekipę do transportu i spakowałem sprzęt. W całej akcji wzięły udział następujące osoby : Wiktor Bolek - kierownik, płetwonurek, Piotr Bator, Adam Borysiewicz, Tomasz Chrul, Krzysztof  Domagała, Dariusz Nowakowski, Piotr Szumny, Piotr Wadowiec - wszyscy Sekcja Grotołazów Wrocław. Częściowo w transporcie pomogło nam jeszcze dwóch kolegów z Głogowa. Całość sprzętu nurkowego zapakowałem w sześć szpejów (worków transportowych) : trzy butle, suchy kombinezon, płetwy i jacket, akumulatory i  automaty. Już w trakcie akcji okazało się, że część osób ma stosunkowo małe doświadczenie. Dla niektórych była to dopiero druga akcja w Tatrach. Przy zaciskach znowu powstały problemy. Kilku zawodników już chciało wracać stwierdziwszy , że nie są w stanie przejść, nie mówiąc już o przeciągnięciu szpejów. W tej sytuacji musiałem wrócić się przez zaciski i przeciągnąć zarówno ludzi jak i sprzęt. Po kilku godzinach walki całe moje wyposażenie dotarło nad lustro wody bez uszczerbku.</p>
<p>Miejsce startu do nurkowanie było bardzo niewygodne. Wprost ze zjazdu na linie lądowało się na stromej i bardzo śliskiej półeczce o wymiarach 1 na 2 metry. Z ledwością mieścił się tu cały sprzęt nurkowy. Suchy kombinezon musiałem zakładać na górze ostatniej studni. Samo przygotowanie do nurkowania zajęło mi blisko dwie godziny i było najbardziej uciążliwą czynnością podczas całej akcji.</p>
<p>Odetchnąłem z ulgą dopiero wtedy, gdy znalazłem się pod wodą. Krystalicznie czysta otchłań pode mną dodawała mi otuchy. Ze względu na silne mrozy niewiele wody wpływało z Ciasnych Kominów do syfonu. Poprzednim razem woda wychlapywana z kałuż zmąciła wstępną studnię. Spłynąłem na -13m. W tym miejscu poprzednio zastabilizowałem poręczówkę. Kilka metrów niżej widać było piaszczyste dno wstępnej studni. Tu zaczynała się dużych rozmiarów pochylnia, 3-4 metry w przekroju. Na skalnej żylecie zostawiłem dodatkową 4l butlę na przewidywana dekompresję. Zapisałem azymut, włączyłem 50W latarkę, ruszyłem w głąb. Płynąłem wzdłuż poręczówki pozostawionej 10 miesięcy wcześniej. Przekrój korytarza na chwilę nieco się zmniejszył do 2 x 2 m. Zauważyłem, że jedna z latarek dająca skoncentrowany snop światła przestała działać. Włączyłem czwarte dodatkowe źródło światła. Dwa pozostałe to 50 W i 20 W latarki zasilane z zewnętrznych akumulatorów.</p>
<p>Zatrzymałem się przy ciężarku, do którego był przywiązany koniec poręczówki. Sprawnie dowiązałem nową linkę z kołowrotka. Rozpocząłem penetrację nieznanego. Podwodny korytarz opadał coraz szybciej w dół. W pewnym momencie przeszedł w pionowy, kilkumetrowy próg. Były tam dogodne występy, na których postanowiłem zastabilizować poręczówkę. Na głębokościomierzu odczytałem -46m, 70 m od powierzchni wzdłuż poręczówki. Zaczynałem już odczuwać pewne oszołomienie narkozą azotową. Zapisałem dane. Pod progiem zaczynała się kolejna pochylnia, biegnąca pod kątem prostym w stosunku do poprzedniego odcinka. Nagle zmniejszyła się ilość światła. Zobaczyłem swobodnie pływający obok mnie przewód od jednego z akumulatorów. Przez chwilę próbowałem włożyć go ponownie, ale maska nieznośnie ograniczała mi widoczność i nie mogłem trafić do gniazdka umieszczonego na pasie. Popłynąłem dalej. Oddychałem z automatu Scubapro. W pewnym momencie poczułem grudki lodu we wdychanym powietrzu. Co gorsza drugi stopień nie zamykał się do końca przy wydechu. Znałem tę sytuację z nurkowań w kamieniołomie. Jeszcze parę oddechów i automat zamarznie w pozycji otwartej i stracę całe powietrze z jednej butli. Wobec tego przeszedłem na Poseidona (Jetstream), a drugi stopień Scubapro odciąłem szybkozłączką. Miałem nadzieję wykorzystać to powietrze podczas powrotu powyżej -40m, gdy już nieco się ogrzeje. Płynąłem dalej. Stres narastał. Pogłębiało się oszołomienie narkozą azotową. Musiałem już natężać całą swoją silną wolę , aby w pełni kontrolować sytuację. Poczułem, że należy zawrócić. Narkoza azotowa objawiła się znacznie płycej niż się spodziewałem. Przyczyną był zapewne stres i olbrzymi wysiłek fizyczny przed samym nurkowaniem. Głębokościomierz wskazywał 51.1 m. Właśnie minąłem na poręczówce marker 95 m. Koniec poręczówki przywiązałem do ciężarka, zapisałem azymut. Poczułem rozluźnienie. Teraz musiałem już "tylko" powrócić na powierzchnię. Powoli przesuwałem się wzdłuż poręczówki. Widoczność nadal była doskonała. Tylko gdzieniegdzie od stropu odpadały płatki błota poruszone pęcherzami wydechowymi. Komputer pokazywał konieczność wykonanie 7 min dekompresji z pierwszym przystankiem na -4m. Będę miał sposobność wykorzystać butlę zostawioną w depozycie. Powoli minąłem głębokość -40m. Postanowiłem sprawdzić Scubapro. Przesunąłem szybkozłączkę i wziąłem oddech. Wszystko było w jak najlepszym porządku. Byłem coraz wyżej. Stopniowo zmniejszałem prędkość wynurzania. Robiłem to znacznie wolniej niż tego wymagał komputer.</p>
<p>Powoli dopłynąłem do butli depozytowej. Postanowiłem spędzić tu trochę czasu, gdy wtem zorientowałem się, że zgasło mi kolejne światło. Z akumulatora wystawały kabelki połączeniowe - awaria nie do naprawienia w grubych 7 mm rękawiczkach neoprenowych. Przez chwilę próbowałem ponownie włożyć wtyczkę do drugiego z akumulatorów, ale znów bezskutecznie. Na szczęście z tego miejsca mogłem się już wynurzyć bezpośrednio na powierzchnię. Widziałem już lustro wody i światło Adasia oczekującego na półeczce. Świadomość tego faktu podziałała uspokajająco. Ostrożnie zdjąłem butlę depozytową z występu skalnego i rozpocząłem dekompresję. Komputer wskazał mi dwa przystanki 3' na 4m i 4' na 2m. Po 32' nurkowania pojawiłem się na powierzchni i odetchnąłem nieświeżym powietrzem. Przy samym syfonie na dnie jaskini cyrkulacja powietrza była bardzo ograniczona. Przebywanie w tym miejscu kilku osób przez dłuższy czas wywoływało zaduch i mgłę pochodzącą z wydechów. Aby nieco oczyścić atmosferę wypuściliśmy część powietrza z butli - mogłem odetchnąć pełną piersią.</p>
<p>Pozostało jeszcze zdjąć z siebie i spakować cały sprzęt. Każdy drobiazg, jeden po drugim. Rozpoczęliśmy retransport. Ci mniej doświadczeni koledzy mieli trudności z przechodzeniem ciasnych miejsc. Przejście Wyżymaczki czy Zacisku Kaczanosia trwało po pół godziny na osobę.  Wydłużyło to znacznie całą akcję. Na powierzchnię wyszliśmy dopiero po 23 godzinach pobytu pod ziemią.</p>
<p>Syfon w Ciasnych Kominach jest jednym z najciekawszym problemów nurkowych w Polsce. Tym bardziej, że jest nadal otwarty. Osiągnięto głębokość -51.1m w odległości 95m od powierzchni. Dalsza eksploracja w tym miejscu będzie wymagała użycie mieszanek, aby zwiększyć bezpieczeństwo poruszania się na takich głębokościach.</p>


<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>