<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Problem eksploracyjny w Dudnicy nadal otwarty
</h1>
<p>Najłatwiej dostępnym miejscem, gdzie można wykonać nurkowanie w korytarzu zalanym po strop jest jaskinia Dudnica, położona w Tatrach nieopodal Kalatówek.</p>
<p>Odkryto ją jeszcze w 1932r., kiedy to Stefan Zwoliński i Józef Dobiecki dotarli do pierwszego syfonu - jeziorka. Jest to bardzo ciekawe miejsce, ponieważ przez szczeliny w stropie słychać szum podziemnego potoku przepływającego po drugiej stronie. Poziom wody w tym syfonie jest zmienny i zależy od pory roku. W czasie stanów powodziowych może podnieść się nawet o 10m, tak że woda wylewa się wtedy z otworu. Natomiast w czasie suszy syfon staje się jeziorkiem i można go przejść wpław. W 1949r. podczas wypompowywania syfonów wstępnych w pobliskiej Jaskini Bystrej, pierwszy syfon w Dudnicy także osuszył się zupełnie. Wtedy to Stefan Zwoliński suchą stopą odkrył za nim kilkudziesięciometrowy korytarz zakończony syfonem nr 2. Dalsza eksploracja była już prowadzona z użyciem techniki nurkowej. W 1965r. członkowie Akademickiego Klubu Podwodnego "Kalmar" pokonali II Syfon (-4m, 8m dług.) i dotarli do trzeciego. W 1970 r. M. Słabik i K. Grajek pokonali III Syfon (-4m, 18m dług.) i stanęli nad Tajemniczą Studnią. W trakcie powrotu awarii uległ automat K. Grajka. Jednak dzięki ofiarności M. Słabika uszedł z życiem. M. Słabik w czasie akcji wielokrotnie pokonywał wyeksplorowane właśnie syfony, aby dostarczyć swemu koledze sprawny aparat. Wyjaśnienia zagadki Tajemniczej Studni dokonano dopiero w 1973r. Płetwonurkowie z Warszawy wyposażeni w stalową drabinkę zeszli w pionie cztery metry i następnie zanurkowali w IV Syfonie, który przy głębokości -7m i długości kilkunastu metrów zakończył się zawaliskiem. Od tego czasu jaskinia służyła przede wszystkim jako miejsce dla treningów. Odbyło się szereg akcji. W ich trakcie stwierdzono, że przy wyższym stanie wody syfony II i III łączą się w jeden, a Tajemnicza Studnia może być całkowicie zalana i nie trzeba wtedy wykorzystywać technik jaskiniowych.</p>
<p>Również i w moim przypadku tak się złożyło, że Dudnica była jedną z pierwszych jaskiń, gdzie oswajałem się z nurkowaniem w korytarzach zalanych po strop.  W grudniu 1991 podczas pokonywania I Syfonu zastanowił mnie fakt, skąd się bierze ten ogromny potok płynący przez całą jaskinię? W krystalicznie czystej wodzie dostrzegłem, że między kamieniami na dnie jest niewielki prześwit, który dalej przechodzi w wąski korytarz. To mógł być właśnie ciąg doprowadzający tę całą wodę. Początkowo nie podjęliśmy tam eksploracji ze względu na zaangażowanie w Śnieżnej Studni oraz na fakt, że większość kolegów, z którymi współpracowałem, nie uwierzyła mi, że można w tym  miejscu posunąć się naprzód.</p>
<p>Dopiero w 1995 udało mi się dwukrotnie zorganizować ekipę transportową i podczas solowych akcji w syfonie wybierałem mozolnie co większe kamienie. Za drugim razem przecisnąłem się nawet do korytarzyka, ale ze względu na brak asekuracji  i niestabilność osuwiska kamieni, które musiałbym zostawić za sobą, nie podjąłem dalszej eksploracji.</p>

<p align=center>
	<a href="./img/dudnica_big.gif" target="_new">
		<img src="./img/dudnica_small.gif" alt="Plan syfonów w jaskini Dudnica." height=413 width=300></a><br>
	<i>Plan syfonów w jaskini Dudnica.</i>
</p>

<p>Pierwsza akcja z prawdziwego zdarzenia została zorganizowana dopiero w lipcu 1996. Na wzięcie udziału w nurkowaniu wyrazili chęć płetwonurkowie z Bydgoszczy : Piotr Śmidoda oraz Andrzej Zaręba, którzy uczestniczyli w Warsztatach Nurkowania Jaskiniowego na Istrii. Członkami ekipy transportowej zostali : Dariusz Bartoszewski, Radosław Paternoga i Wojciech Piotrowicz z Sopotu.</p>
<p>W lipcu stan wody jest zawsze wysoki. Tak było i tym razem. I Syfon był zamknięty na głucho i nie dochodził stamtąd żaden odgłos szalejącego za ściana podziemnego potoku. Jeziorko wstępne miało niewielkie rozmiary i do tego gliniaste dno, tak że szybko uległo zmąceniu. Widoczność poprawiała się dopiero po wpłynięciu do jeziorka po drugiej stronie, gdzie wartki strumień wody szybko wymywał cały mąt. Dla chłopców z Bydgoszczy było to pierwsze nurkowanie w jaskini. Przejście ciasnego odcinka z dwoma 8l butlami, przy prawie zerowej widoczności było dla nich mocnym przeżyciem.</p>
<p>Po przejściu na druga strona przycupnęliśmy na chwilkę na niewielkiej półeczce. Stojąc po pas w wodzie zbieraliśmy siły na właściwą eksplorację. Na przodek prowadziła biała poręczówka, którą zostawiłem tu ponad rok temu. Natomiast droga do wyjścia była oznaczona czerwoną linką. Rozpoczęliśmy przerzucanie kamieni pod wodą . Prąd był bardzo silny! Małe kamyki poruszone z dna ulatywały porywane strumieniem wody. Okazało się, że biała poręczówka jest w jednym miejscu przetarta. Luźno unoszące się kawałki linki pociąłem na krótkie odcinki, aby uniknąć zaplątania. Jest w sumie bardzo prosty "chwyt", którego nauczyłem się na kursie we Francji.</p>
<p>Po 10 minutach pracy na głębokości - 2.8 m uznałem, że przejście jest bezpieczne i postanowiłem wejść w dziewiczy teren rozwijając nową poręczówkę z kołowrotka. Prąd stał się jeszcze silniejszy. Z najwyższą trudnością posuwałem się naprzód. Wykorzystywałem wszystkie dostępne stopnie i chwyty. Płetwy w tych warunkach byłyby zupełnie nieprzydatne. Ważniejsza była znajomość technik wspinaczkowych. Najciaśniej było na początku. Dalej przekrój powiększał się. Dno zaczęło być lite - pozbawione luźnych kamieni. Prąd nieco zelżał. Korytarz łagodnie opadał w dół. Znalazłem się w komorze, którą dostrzegłem jeszcze na poprzedniej akcji. Nie była aż tak obszerna jak to sobie wyobrażałem, ale mogłem swobodnie obrócić się. Głębokościomierz pokazywał -4.6 m. Po prawej zobaczyłem ciasną rurę o trójkątnym przekroju, która schodziła dalej w dół. Wejście w nią wymagałoby chyba odpięcia butli. Poczułem ogarniające powoli zimno. Szybko przepływająca woda o temperaturze 3 OC wychładzała mój organizm. W tym momencie zorientowałem się, że popełniłem błąd. Zaglądając do trójkątnej rury miałem poręczówkę po swojej zewnętrznej stronie. W wyniku tego linka weszła mi pod butlę. Nie mogłem natychmiast rozpocząć powrotu! Mogłem ciąć linkę - co było jednak ostatecznością, albo spróbować wyplątać się. Panika powolutku zaczynała narastać. Było coraz zimniej. Wziąłem się jeszcze w garść. Dałem więcej luzu na kołowrotku i wyciągnąłem linkę spod butli. Następnie wybrałem powstały luz i zastabilizowałem poręczówkę z gumki. Gdy odciąłem kołowrotek, poczułem ulgę. Mogłem już wracać. Pozwoliłem unieść się prądowi. Do góry poruszałem się bez wysiłku. Zbyt łatwo! W końcowym, ciaśniejszym fragmencie korytarza, prąd przytulił mnie do stropu. Poczułem jak mój zewnętrzny ortalionowy kombinezon drze się na wystających ze stropu żyletach. Nagle poczułem opór, którego nie mogłem już pokonać przez dalsze rozdzieranie. Widziałem już światła i twarze czekających kolegów. Czyżbym miał tu utknąć o metr od światła jeziorka? Udało mi się wykręcić rękę na plecy i odczepić taśmę, która zaczepiła się o występ skalny. Wypłynąłem do jeziorka. Szczękając zębami, drżącym głosem powiedziałem chłopakom, że płynę do wyjścia, a jak chcą to niech jeszcze zobaczą nowy korytarz i też wracają.</p> 
<p>Wróciłem po czerwonej poręczówce. Po wyjściu z wody zrobiło mi się znacznie cieplej. Nurkowanie trwało 22 minuty. Zużyłem prawie połowę początkowego powietrza. Po kilku bulgotach Piotrek i Andrzej bezpiecznie powrócili zza syfonu. Rozpoczęliśmy retransport.</p> 
<p>Pomimo wielu akcji nurkowych , które odbyły się w Dudnicy, można jeszcze tam coś nowego odkryć. Eksploracja nie jest łatwa ze względu na ciasności i silny prąd. Natomiast niewątpliwym plusem jest doskonała widoczność. W zimie prąd na pewno będzie mniejszy, a ciasności staną się łatwiejsze, gdy odepnie się butle. Eksploracja w tej jaskini może przynieść niespodziankę w postaci uzyskania mitycznego połączenia z Jaskinią Bystrej, co przewidywał jeszcze w latach 30-tych nestor polskiej speleologii  : Stefan Zwoliński.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>