<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Sztolnia w Kowarach
</h1>

<p>Od czasów, gdy w naszej Sekcji zaczęliśmy zajmować się na poważnie nurkowaniem w jaskiniach, szukamy na terenie Dolnego Śląska podziemnych, zalanych obiektów, gdzie w bliskiej odległości od domu można oswajać się z tym niedostępnym środowiskiem. Przy tej okazji nawiązaliśmy kontakt z chiroptereologami, czyli ludźmi, którzy zajmują się badaniami i ochroną nietoperzy. Ze względu na charakter pracy znają oni wiele podziemnych obiektów, gdzie mają swe kryjówki te sympatyczne ssaki. Część z nich jest zalana i może być przydatna do naszych celów. W ten sposób dowiedzieliśmy się o starych kopalniach w rejonie Kowar. 
<p>Pewnego mglistego, styczniowego poranka 1994r. grotołazi i płetwonurkowie spotkali się z miłośnikami nietoperzy gdzieś w Karpaczu. Po czym, już razem, pojechaliśmy do jednego z dostępnych wejść. Obiekt znajdował się w zagajniku, naprzeciw hałdy w Kowarach Górnych. Sztolnia składała się z dwu poziomych chodników o długości kilku metrów. Na końcu znajdowała się studzienka (o przekroju 1x1.5 m), zabezpieczona poziomą, stalową kratą, w której były jednak otwarte drzwiczki. Woda zaczynała się ok. 2m poniżej kraty. Po jednej stronie studzienki była drabinka, co ułatwiło dotarcie do lustra wody.
<p>Jako pierszy nurkował Wacław Kozieł. Okazało się, że przejście przez otwór w kracie z butlami na plecach sprawiło mu sporo kłopotów. W końcu jednak dotarł do wody. Po uporządkowaniu sprzętu zanurzuł się. Stojąc na kracie widzieliśmy jak jego światlo powoli oddala się pod wodą wśród strumieni pęcherzyków powietrza. Jednak po chwili wynurzył się. Powiedział, że wzdłuż drabinki ciągnie się w dół jakaś biała nitka, która może być podłączona do zapalnika ukrytej bomby. Niemcy, skrzętnie pilnujący swoich tajemnic, mogli zastawić taką pułapkę. Wyjaśniliśmy Wackowi, że to nie możliwe, bo ta kopalnia była budowana w latach 50-tych obecnego stulecia. To go przekonało i ponownie zanurzył się. Jego światła stawały się coraz mniej wyraźne. Nikła poświata po chwili zgasła i tylko wypływające pęcherze świadczyły, że Wacek jeszcze żyje. Po chwili jednak i one zniknęły. Wacek musiał wpłynąć w boczny korytarz. Zaczęliśmy rozmawiać o błahych sprawach, a czas powoli mijał. Po kilku minutach zaczęliśmy się niepokoić. Już zamierzałem zakładać butle i iść za Wackiem, gdy w studzience pojawiły się pęcherze i światło. Po chwili Wacek już był na powierzchni. 
<p>Okazało się, że studnia ma ok. 17m słupa wody. Na dnie odchodził boczny korytarz, który od razu doprowadzał do komory o drewniano-kamiennym stropie. Wejście do salki zagradzała belka zwisająca ukośnie ze stropu, ktory wyglądał, jakby miał zaraz runąć. W środku salki był otwór kolejnej studni - również zakratowany, jednak z otwartymi drzwiczkami. Wacek stwierdził, że z butlą na plecach na pewno nie przejdzie przez ciasne drzwiczki pod wodą i postanowił wycofać się, uważając przy tym by nie zmącić wody. 
<p>Ja nurkowałem jako następny. Wziąłem ze sobą sonar dla pomiaru odległości. Mocno wciągnąłem brzuch przechodząc przez kratę i zszedłem do wody. Drabinka doprowadzała aż na samo dno studni, tak że nie musieliśmy używać płetw. Zanurzyłem się. Ogarnęło mnie zimno. Znalazłem się w innym, niż na powierzchni, środowisku. Wszystkie zmysły działały inaczej. Byłem w szoku. Chciałem stamtąd wyjść. Zatrzymałem się na chwilę. Pomyślałem o poprzednich nurkowaniach. Organizm powoli przyzwyczaił się do nowej sytuacji. Mogłem kontynuować nurkowanie. Zszedłem na dno studni i zobaczyłem boczny korytarz. Woda była klarowna. Wackowi rzeczywiście udało się jej nie zmącić. Wszedłem w korytarz w zapieraczce pod stropem - jak pająk, by nie poruszyć mułu z dna. Wejście do następnej komory zagradzała stercząca ze stropu belka. Udało mi się ostrożnie nad nią przepłynąć. Dociągnąłem się do kraty. Spróbowałem wysondować sonarem głębokość następnej studzienki. Każdy odczyt był inny. Domyśliłem się, że zależało to od odpowiedniego nakierowania wiązki ultradźwięków. Jeżeli nie została ona wysłana dokładnie w osi studni, to odbijała się od ściany i wskazywana odległość była mniejsza. Za głębokość studni należało przyjąć maksymalną odczytaną wartość. Wynosiła ona 9.7m. Po tym stwierdzeniu postanowiłem przejść przez kratę. Ostrożnie ustawiłem się na drabince, która schodziła w dół studni. Kontrolując z tyłu ręką położenie butli przeszedłem przez kratę. Byłem na -18 m. Nie schodziłem dalej. Przestraszyłem się, że podczas wyjścia nie trafię zaworami butli w światło otworu w kracie i zostanę tam na zawsze. Powróciłem do pierwszej studni. Tym razem już odbijałem się od dna, co kompletnie zmąciło wodę. Zmierzyłem jeszcze sonarem długość korytarzyka. Maksymalny odczyt wyniósł 2.1 m. Powoli zacząłem wychodzić. Odrywające się od drabinki płatki rdzy niweczyły resztki widoczności. Na wszelki wypadek zatrzymałem się na trzech metrach i w końcu wynurzyłem się. 
<p>Było to bardzo trudne nurkowanie, wymagające olbrzymiej odporności psychicznej. Zalana część sztolni ma skomplikowany kształt i ciasne kratki na sporej już głębokości. Nie udało się nam jeszcze zbadać jej do końca. Według planów jedna z kopalni na tym terenie miałaby mieć chodniki na głębokości -520m. Jednak nie znamy żadnego wejścia prowadzącego do niej. Być może penetrowany obiekt jest kanałem wentylacyjnym prowadzącym do takiego właśnie kompleksu.

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>