<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Nurkować w jaskiniach latem ? - ależ tak !
</h1>

<p>Już od prawie czterech lat trwa uporczywa eksploracja Syfonu Drzemiącego w Śnieżnej Studni. Zmęczeni wyczerpującymi podejściami w zimie postanowiliśmy wykorzystać lato do kolejnych ataków, zwłaszcza, że poziom wody tylko niezancznie zależał od pory roku. Kolejna akcja wydawała się łatwa do przeprowadzenia. Podczas ostatniego nurkowania (GiA 14) Michał założył poręczówkę i pozostawił na jej końcu kołowrotek z co najmniej 100 metrami linki. Jednak znając z poprzednich akcji zaciekłość z jaką Góra broni swego wnętrza przygotowałem się bardzo dokładnie. Aby nie dać się zaskoczyć nieprzewidzianym sytuacjom, przez całą wiosnę trenowałem nurkowanie w sztolniach i na wodach otwartych. Zaporęczowałem w kamieniołomie tor odpowiadający przebiegowi poręczówki w syfonie. Wymyśliłem i przećwiczyłem stabilizowanie linki za pomocą szabli błotnej - co miało się przydać w Komorze Wacka. Zdobyłem program komputerowy pozwalający symulować nurkowanie, dzięki czemu oceniłem krzywą dekokmpresji zerowej oraz ilość potrzebnego powietrza na przewidywany zakres penetracji. Akcję postanowiłem przeprowadzić podczas lipcowego obozu tatarzańskiego Sekcji Grotołazów, tak aby nie mieć trudności ze znalezieniem chętnych do transportu. Sądziłem, że wszystko jest przemyślane i przygotowane i absolutnie nic nie jest w stanie mnie zaskoczyć. Okazało się jednak, że tym razem Góra była górą. 
<p>Już zjeżdżając lodospad stwierdziłem ze zdumieniem, że nie ma kilkumetrowego lodowego progu. Na dno sali schodziło się po śnieżnej pochylni. Stojąc na dole zobaczyłem u swych stóp półeczkę, która normalnie jest około 1,5 m nad spągiem. Wynikało stąd, że przejście do Studni Kozika jest zasypane śniegiem. Ponieważ byliśmy grupą zaprawioną w kopaniu igloo pod Wielką Śnieżną, postanowiliśmy odkopać przełaz. Nie mając żadnych narzędzi usuwaliśmy śnieg przy pomocy ostrych kamieni i kasku. Wykopaliśmy studzienkę głęboką na 1,5 m i na tym poziomie natrafiliśmy na lód, który okazał się zbyt twardy do skruszenia.
<p>Najprawdopodobniej podczas wiosennych gwałtownych opadów nawiało do otworu aż tyle śniegu. Chodzę do tej jaskini od sześciu lat i jeszcze nie spotkałem się z taką sytuacją. Potwierdzają to zakopiańczycy, którzy twierdzą, że przejście było drożne od 07.09.1979 roku, kiedy to A. Kozik stwierdził gwałtowne cofnięcie się czoła lodospadu i przeszedł przełaz. Znając historię eksploracji nie można wykluczyć, że jaskinia będzie zamknięta przez dłuższy okres czasu. 
<p>W Sali z Madonną pod ścianamizawsze były głębokie szczeliny, które tym razem wypełniała woda ze śnieżnym błotem. Świadczy to o tym, że nie było odpływu do wnętrza jaskini. Mając do czynienia ze Śnieżną Studnią od kilku lat muszę przyznać, że broni ona swego wnętrza w sposób   <b>bezwzględny</b>.
<p>Na szczęście w Śnieżnej Studni nie został zdeponowany żaden sprzęt (oprócz ciężarków) i praktycznie wszystko co potrzebne do nurkowania miałem na Polanie Rogoźniczańskiej. Aby wykorzystać przywieziony sprzęt, postanowiłem przeprowadzić od dawna odkładaną akcję w Dudnicy. W tej jaskini, w przeciwieństwie do Syfony Drzemiącego, występuje ciągły przepływ wody, którego wielkość zależy od pory roku. Stąd też nurkowano tu jedynie w zimie. Nie mając nic do stracenia postanowiłem zaryzykować. 
<p>Gdy doszedłem do syfonu uderzyła mnie panująca w tym miejscu cisza. Poziom wody musiał być na tyle wysoki, że zostały zakryte szczeliny, przez które było słychąc huk wody przepływającej przez meander. Usłyszałem go dopiero, gdy zanurzyłem głowę. Po chwili wynurzyłem się po drugiej stronie. Przez meander napierała olbrzymia masa wody. Miałem problemy z utrzymaniem równowagi i z trudnością zamocowałem poręczówkę. Ponownie zanurzyłem się w syfonie by zbadać miejsce, z którego ta woda wypływa - co było głównym celem eksploracji. Tak jak przypuszczałem otwór był częściowo zawalony kamieniami. Strumień płynącej wody miał olbrzymią siłę. Ąeby posuwać się na przód musiałem korzystać ze stopni i chwytów. Wyciągnięcie ręki do przodu wymagało olbrzymiego wysiłku. Co chwila odginało mi ustnik w wargach i dostawałem wodę wraz z powietrzem. Natomiast gdy ustawiłem się prostopadle do strugi, ciśnienie dynamiczne wody powodowało ugięcie membrany w drugim stopniu i powietrze uciekało z automatu. Głowę musiałem trzymać przekrzywioną na bok. Nigdy dotąd w swojej praktyce nurkowej nie spotkałem się z tak silnym prądem. Woda napływająca z wnętrza jaskini była krystalicznie czysta - stąd orientacja była bardzo łatwa. Moim głównym celem było usunięcie kamieni zagradzających dalsze przejście. Początkowo chciałem użyć liny do ich wyciągania, ale okazało się, że mniejsze kamienie dygotały w tym prądzie jak papierki na wietrze. Wystarczyło je tylko lekko przemieścić i same ulatywały z najciaśniejszego miejsca. Natomiast duże można było wziąść w ręce i dać się porwać strudze, która wyrzucała nas w stronę meandra. Po około 10 min. takiej pracy odsłoniłem cały przekrój korytarza. Była to rura o średnicy około 1m, która zaraz skręcała w prawo opadając ciągle w dół. Po kilku metrach było widać rozszerzenie i jakby studzienkę. Wchodząc do tej rury zatykałem swoim ciałem praktycznie cały przekrój przepływu. Opory poruszania się gwałtownie wzrosły. Momentami zaczynało to przypominać klasyczną wspinaczkę na piątkowej drodze z 30-kilogramowym plecakiem. W tych warunkach postanowiłem wycofać się, tym bardziej że nie miałem odpowiedniej poręczówki i tylko jeden aparat. Przedtem jednak dokonałem ciekawej obserwacji biologicznej. W miejscu największego przewężenia, na litych ścianach zauważyłem bladozielone - coś. W pierwszej chwili myślałem, że to skrawki folii, ale zastanowiło mnie jak one się tam pozahaczały? Odkryłem, że muszą to chyba być glony. Olbrzymi strumień wody przynosi im cząsteczki, bądź co bądź, rozrzedzonego pożywienia. Nikła zieloność pewnie brała się stąd, że do syfonu musi jeszcze docierać światło z otworu. Jest to chyba jedyne tego typu stanowisko w Polsce. 
<p>Problem w Pierwszym Syfonie w Dudnicy został otwarty. Odkryty korytarz daje szansę na połączenie z jaskinią Bystrej. Dalszą eksploracją trzeba lepiej przygotować i poczekać na łagodniejsze warunki. Aby lepiej wyobrazić sobie, to co się tam dzieje wystarczy pomyśleć, że cała woda wypływająca z wywierzyska  przepływa przez rurę ośrednicy jednego metra. 

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>