<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Znów w Syfonie Drzemiącym
</h1>

<p>Między świętami Bożego Narodzenia a Sylwestrem roku 1994 kontynuowaliśmy eksplorację w Syfonie Drzemiącym w Śnieżnej Studni. Akcja była przygotowywana niemal przez cały rok. W jaskini znajdowały się butle zaniesione jeszcze w marcu oraz inne depozyty zanoszone później przy różnych okazjach. Wymieniliśmy część stałego oporęczowania na liny otrzymane ze sklepu Cave-Sport. Akcję przesuwaliśmy wielokrotnie z różnych powodów. W lipcu zrezygnowaliśmy z akcji ze względu na śmierć Przemka Rogowskiego w Wielkiej Śnieżnej. We wrześniu i listopadzie nie udało się skompletować odpowiedniego zespołu. Dopiero obecność w Tatrach znacznej liczby grotołazów z okazji Obozu Sylwestrowego pozwoliła na przeprowadzenie akcji. 
<p>Do jaskini wyruszyliśmy o poranku, we wtorek 27.12.94 i po kilku godzinach ubijania śniegu dotarliśmy do otworu. Biwak założyliśmy jak zwykle na głębokości -500m. Nurkowanie rozpoczęliśmy w środę po południu, po zaniesieniu całego sprzętu nad syfon (szczegółowy harmonogram jest zamieszczony w zestawieniu obok). 
Zgodnie z wcześniejszymi ustaleniami nurkował Michał Stajszczyk, a ja go asekurowałem. Przygotowaliśmy dla niego dwie butle 8l i 4l ze 160 atm, z automatami Poseidon Cyklon 300 i Sherwood Blizzard Magnum, a dla nurka asekurującego 4l z automatem Scubapro MK10/R190. Tym razem postanowiliśmy, że płetwonurek eksplorujący będzie sam sobie odwijał linkę z kołowrotka. Dzięki temu można poręczówkę odpowiednio stabilizować, a po zakończeniu nurkowania łatwiej jest ją zostawić w syfonie.
<p>Po uporaniu się z błotem i sprzętem Michał zanurzył się w początkowo krystalicznej wodzie i odpłynął na drugi koniec jeziorka. Stojąc na błotnistej półeczce kontrolowałem naciągnięcie poręczówki. W razie czego miałem likwidować powstający luz. Michał zszedł pod wodę. Przez chwilę bąble powietrza wypływały na powierzchnię, póŚniej wszystko ucichło. Poręczówka była słabo naciągnięta. Wybierałem co raz to nowy zwój luzu. W końcu miałem już w ręku pierwszy marker oznaczający dziesięć metrów. Nieoczekiwanie w jeziorku wynurzył się Michał, po niespełna minucie pobytu pod wodą. Nie udało mu się wpłynąć do głównego ciągu syfonu. Popełnił ten sam błąd co ja poprzednim razem. Wszedł w wąski korytarzyk stromo opadający w dół. Wejście do właściwego syfonu było nieco dalej. Michał odpoczął, wziął się w garść i ponownie zanurkował po drugiej stronie jeziorka. Tym razem poręczówka była przez cały czas prawidłowo naciągnięta. Wypuściłem cały wybrany wcześniej luz. Po upływie kilku minut, poczułem zmianę w napięciu linki. Wyczuwałem miarowe, niezbyt mocne pociągnięcia. Musiał już wracać. Po upływie 13 minut od zanurzenia Michał wypłynął z syfonu. Usłyszałem ciągłe, świszczące bąblowanie powietrza - tak różne od regularnych bąbli wydechowych. Mogło to być spowodowane tylko awarią aparatu! I rzeczywiście spod automatu rezerwowej 4l butli wydostawał się strumień bąbelków. Gdy Michał już trochę ochłonął ze stresu, udało się ustalić spójną wersję wydarzeń. 
<p>Na samym początku, w kompletnie zmąconej wodzie, Michał zdołał wpłynąć do właściwego syfonu. Gdzieś na głębokości 7m dopłynął do czoła zmąconej wody i ujrzał przestronny korytarz w świetle swojej silnej 15 watowej latarki, wypożyczonej dzięki uprzejmości sklepu Ocean Sub. Po lewej stronie korytarza wystawała z dna spora ostroga skalna. Za nią główny ciąg syfonu opadał stromo w dół. Michał wpłynął tam, pamiętając by w drodze powrotnej nie dostać się między tę ostrogę a ścianę. Poniżej tego progu korytarz był nadal obszerny 4x5m i szedł dalej poziomo na głebokości ok. 21 metrów. W pewnym momencie Michał usłyszał nad uchem bąblowanie dochodzące z zamocowanych na plecach butlach. Stwierdził, że dzieje się coś niedobrego i postanowił zawrócić. W świetle latarki zobaczył, że korytarz wznosi się dalej nieco do góry, na przestrzeni około 10m. Dalszy widok zasłaniał strop. Zawiązał na poręczówce kluczkę i przełożył przez nią pętelkę z ciężarkiem, po czym zostawił cały kołowrotek na końcu wyeksplorowanego odcinka. Początkowo wracał w klarownej wodzie. Pierwszy marker, do którego dopłynął, miał 80m. Jednak po kilkunastu metrach widoczność zmalała poniżej 0.5 metra. Dalej, choć w wielkim stresie, dopłynął bez większych przeszkód do jeziorka. W ośmiolitrowej butli zostało mu tylko 60 atm. 
<p>Pomimo olbrzymiego wysiłku włożonego w całą akcję, rezultat jest stosunkowo skromny. Jaskinia nie została pogłębiona, syfon został wydłużony o 15m i liczy sobie teraz około 65m przy maksymalnej głębokości 22. Wydaje się, że osiągnąliśmy już jego przegięcie, gdyż dalej korytarz zaczyna się powoli wznosić. 
<p>Żadna z przeprowadzonych do tej pory akcji nurkowych nie przebiegła płynnie. Zawsze coś musiało nawalić. Ale to chyba określa rangę tego problemu. Również podczas wychodzenia przeżyliśmy sporo emocji. Jeden z kolegów nieostrożnie spuścił lawinę kamieni w 200-metrowej Studni Wazeliniarzy. Pozostali zamarli z przerażenia na poniższych przepinkach. Dudniący łoskot kamieni, spadających przez kilkadziesiąt sekund pionową studnią, był obezwładniający. Ja sam chwyciłem się przypadkowego chwytu na ścianie. Miałem nadzieję, że utrzyma mnie, gdyby spadające kamienie przecięły linę, na której wisiałem. Myślałem również, czy by na tę okoliczność nie wpiąć odwrotnie poignee i wtedy ewentualnie przeżyć lot w oparciu o dolną przepinkę - jeśli oczywiście statyczna lina wytrzymałaby lot o współczynniku równym dwa. Na szczęście kamienie zatrzymały się na półce nade mną. Do mnie doleciał jedynie kamienny pył i olbrzymia ilość strachu. Kilku kolegów zostało niegroŚnie trafionych. Marcin Przybyszewski, który był bezpośrednio nade mną, dostał dwa razy w kask i przez co najmniej dziesięć minut nie mógł powstrzymać potoku słów wypływających z jego ust. Na szczęście żadna z lin nie została uszkodzona. Kolejny horrorek czekał nas jeszcze na powierzchni. Z otworu jaskini wychodzi się po linie nad dwustumetrową ekspozycją. W jednym miejscu lina ta była uszkodzona i zabezpieczona węzełkiem. Jednak jeden z kolegów, któremu najwyraŚniej przepinki sprawiają trudność, postanowił uprościć sobie sprawę i rozwiązał zabezpieczenie. Każdy, kto po nim wychodził, w razie omsknięcia się, mógł zerwać linę i odfrunąć w kierunku Niżniej świstówki. Na szczęście tym razem obyło się bez ofiar. Poza tym pogoda nam dopisała. Widoczność była idealna, choć bez słońca. śniegu było niewiele i już bez większych stresów dotarliśmy do "Harnasia". 
<p>Eksploracja w Syfonie Drzemiącym jest jednym z bardziej intrygujących problemów na terenie naszego kraju. Jest jednak pewne, że uzyskanie tutaj dalszego postępu będzie wymagało hektolitrów potu wyciśniętego z dziesiątków niewinnych grotołazów.

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>