<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,5,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Srebrna Góra - poligon doświadczalny
</h1>

<p>Jesienią 1997 roku powróciliśmy do studni w Srebrnej Górze. Zaletą tego miejsca jest stosunkowo łatwo dostępna duża głębokość. Do przeprowadzenia tutaj treningowych zanurzeń skłoniły nas perspektywy eksploracji zalanych ciągów na dnie Ciasnych Kominów w Jaskini Miętusiej. Podczas akcji na przełomie 96/97 główna przeszkodą w osiąganiu większych głębokości była narkoza azotowa. W czasie tej akcji ustanowiono rekord Polski w nurkowaniu jaskiniowym na -51m. Jednak w dalszym ciągu istnieje możliwość popłynięcia dalej. Fakt wystąpienia ostrej narkozy azotowej już na 50m był spowodowany stresem związanym z nurkowaniem w zamkniętych przestrzeniach oraz olbrzymim wysiłkiem fizycznym podczas drogi dojścia do syfonu. Są to czynniki, których nie sposób ominąć. Stąd też jedyna możliwością dalszej eksploracji jest opanowanie techniki nurkowania na mieszankach. Nurkowie jaskiniowi na Florydzie zalecają przechodzenie na trimix już nawet na 40m.</p>
<p>Początkowo wykonaliśmy szereg próbnych zanurzeń na trimixie na głębokościach do czterdziestu paru metrów. Jednak tu jeszcze trudno było wyczuć zjawisko eliminowania narkozy azotowej. Do pełnego sprawdzenia opanowanej techniki potrzebna była większa głębokość. I tę znaleźliśmy w Srebrnej Górze.</p>
<p>Zaplanowaliśmy zanurzenia na -70m. Trimix sporządziliśmy mieszając hel i powietrze na podstawie ciśnienia. Następnie kontrolowaliśmy zawartość tlenu czujnikiem elektrochemicznym. Ze względu na stały skład powietrza dawało to jednoznacznie zawartość helu w mieszance. Skład był tak dobrany, aby na maksymalnej głębokości ekwiwalentna głębokość narkotyczna (END - equivalent narcossis depth) nie przekraczała 40m. Użycie mieszanek było zaplanowane w sposób następujący : na głębokościach do -50m oddychaliśmy powietrzem, poniżej trimixem 13% O2, 38% He, 49% N2, dekompresję na głębokości 3 m zamierzaliśmy wykonać na nitroxie 40% O2. Dla tak zadanego profilu nurkowania zostały wygenerowane tabele dekompresyjne za pomocą symulacji komputerowej. Oczywiście tabele te nie uwzględniały wszystkich możliwych wariantów. Harmonogramy dekompresji wyznaczono dla różnych maksymalnych głębokości i dla różnego czasu oddychania trimixem. W związku z tym istniała konieczność precyzyjnego dotrzymania pozostałych parametrów profilu nurkowego - zwłaszcza podczas zanurzania i wynurzania. Ewentualnie można było dopuścić tylko takie odstępstwa, które zmniejszałyby ekspozycję na saturację.</p>
<p>Po przygotowaniu mieszanek i całego sprzętu jaskiniowego pozostawało już tylko zanieść go na górę do fortu. Dokonaliśmy tego dzięki pomocy : Romka, Joli, Łukasza, Michała Wenclów, Ryśka Kubackiego, Rafała Szczota i Beaty Bednarskiej. W zanurzeniach wzięli udział : Wiktor Bolek, Michał Stajszczyk, Krzysztof Strama, Norbert Ziober. W sumie wykonaliśmy dziewięć osobozanurzeń podczas trzech różnych wyjazdów.</p>
<p>Po tych wszystkich niebanalnych przygotowaniach ubraliśmy się w sprzęt i stanęliśmy nad krawędzią studni. Okazało się, że poziom wody jest o kilka metrów wyższy niż poprzednio - zapewne po lipcowych powodziach. Dzięki temu zjazd na linie był krótszy, ale i maksymalna głębokość stawała się większa.</p>
<p>Podczas zanurzenia kontrolnego podczepiłem butlę z nitroxem na 3m. Po ostatecznym sprawdzeniu sprzętu rozpocząłem zanurzenie oddychając powietrzem. Na -50m znalazłem się po planowanych 4 minutach. Wyrównałem pływalność. Ostrożnie wymieniłem ustnik i zacząłem oddychać trimixem. Cały czas w napięciu obserwowałem reakcje swojego organizmu. Nie działo się nic szczególnego. Dopiero po kilku oddechach zauważyłem różnicę w wyglądzie ściany studni. Zacząłem dostrzegać drobne szczeliny i odkruszenia w miejscach, które wcześniej uznawałem za jednorodne. Przy mniejszym ciśnieniu parcjalnym azotu, do mózgu zaczynało docierać więcej informacji. Przy lekkiej narkozie azotowej możemy nie zdawać sobie sprawy z ograniczonej liczby bodźców, które do nas docierają. Można to sobie uświadomić dopiero po przejściu na trimix. Moje reakcje były niemal dokładnie takie, jak to opisywał Rob Palmer. Twierdził on, że po trzech oddechach  mieszanka helową umysł "oczyszcza się".</p>
<p>Zacząłem ponownie zanurzać się. Oddychanie trimixem okazało się dosyć kłopotliwe. Ze względu na duże opory było to raczej ssanie. Akurat do tej butli niezbyt szczęśliwie wybrałem automat Scubapro R190. Natomiast Poseidona użyłem do butli z powietrzem, aby mieć pewność, że w razie czego tu wszystko będzie działać poprawnie. Znalazłem się na 70m. Dno było widoczne poniżej moich płetw - nieco głębiej niż planowana głębokość maksymalna. Nie mogłem sobie odmówić satysfakcji postawienia nogi na dnie, które już było w zasięgu światła. Tym samym z pełną świadomością zdecydowałem się na odbywanie dłuższej dekompresji. Na dnie były duże kamienie tworzące między sobą spore komory, do których można było włożyć rękę. Maksymalna głębokość wyniosła -72.1 m.</p>
<p>Rozpocząłem wynurzanie. Na -50m spokojnie przeszedłem na powietrze. Według tabeli musiałem wykonać dwa przystanki : 2' na 6m oraz 6' na 3m. Jednak postanowiłem wykonywać krótkie przystanki już od 15m. Pełny przebieg dekompresji prezentuje profil zamieszczony obok. Na 3m oddychając nitroxem spędziłem czas przewidziany dla dekompresji powietrznej. Był tylko o 2 minuty dłuższy. W ten sposób zwiększałem swój poziom bezpieczeństwa.</p>
<p>Podczas kolejnych prób wszyscy osiągnęli kilkakrotnie dno, później wydłużaliśmy czasy pobytu na dnie. W żadnym z dziewięciu przeprowadzonych zanurzeń nie wystąpiły objawy choroby dekompresyjnej.</p>
<p>Wydaje się, że oswoiliśmy wilka w postaci nurkowań na trimixie. Dużą trudnością pozostaje jednak nadal sztywny profil, dla którego są sporządzone tabele. W przypadku znacznych odstępstw Anglicy postępowali w następujący sposób : płetwonurek zbliżający się do przystanków dekompresyjnych przekazywał zapis swojego profilu na powierzchnię, np. za pomocą tabliczki lub w komputerze nurkowym. Na powierzchni ten profil był wprowadzany do laptopa, który generował wymagany harmonogram dekompresji. Taka informacja trafiała do płetwonurka oczekującego na bezpiecznej głębokości. Jest to dosyć skomplikowana procedura. Znacznym ułatwieniem byłoby wprowadzenie komputerów nurkowych obliczających dekompresję przy oddychaniu różnymi mieszankami podczas jednego nurkowania.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>