<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,4,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Warsztaty nurkowania jaskiniowego GĘBCZYCE 2003
</h1>
<h3>Relacja z warsztatów nurkowania jaskiniowego z punktu widzenia „Laski” członka Stajni Kleina. *)</h3>
<p>Przyjeżdżamy ... Tu zapadam w zamyślenie. O kurcze, jak na parkingu w centrum miasta. Z tego co pamiętam to na warsztatach miało być góra 14 osób. No, ale nic to może to wczasowicze. Wysiadamy sobie spokojnie, oglądamy z góry jeziorko, poznajemy znajome ryjki, idylla. Jakaś mila Pani burzy nasz spokój zaprzątając głowy sprawami organizacyjnymi, wszystko idzie jak po maśle myślę sobie pięknie, fajna organizacja.</p>

<p>Szef zamieszania czyli Wiktor B. oznajmia, że za czas jakiś zamierza wykładać, zgadzamy się wiec na to i przystajemy bo w końcu przyjechaliśmy tu po wiedzę.</p>

<p>Wiktor zaczyna wykład o konfiguracji sprzętowej, tej znanej nam z dwoma butlami na plecach,  wysłuchujemy i od czasu do czasu kręcimy nosem ze względu na DIR poprawność. Odpadają nam z użycia niektóre gadżety takie jak manifold <i>(łącznik międzybutlowy – przyp. W.B.)</i>, ale za to mamy dodatkowy manometr, ładna gumkę na szyi, i sznureczki z gumeczkami na płetewki, po to, aby nam się za bardzo pod woda nie nudziło ;). Wiktor jest w miarę ugodowym człowiekiem, lecz dba o nasze bezpieczeństwo i na niektóre rzeczy się nie zgadza, w końcu osiągamy kompromis.</p>
<p>Po Wiktorze przemawia Pszczółek czyli Andrzej Szerszeń i ilustruje nam jak może wyglądać poręczówka, jak oznaczać powrót do domeczku, ciągi boczne i jak stabilizować ten sznureczek żeby był on poręczówka a nie flakiem, po Jędrku miejsce na mównicy zajmuje Mirek Kopertowski i wyjaśnia nam zasady kartowania. Jeśli ktoś nie był harcerzem, to może mieć problem. Mirek kończy.  Zapada konsternacja ..... jak to było? Wstaje Jacek Trembowelski i  rysuje na tablicy przykład i pyta Mirka czy to dobrze zrozumiał. Każdy w tym czasie przygląda się i udaje ze rozumie. Czy zrozumiał okaże  się później na ćwiczeniach – he, he.</p>
<p>Po wykładach mamy czas na konfigurowanie sprzętu według dyrektyw Wiktora, u mnie jest kilka poprawek, w miedzy czasie robimy sobie kilka głupich fotek a co weseli jesteśmy. Sprzęt sprawdzony zbliżył się standardami do jaskiniowego możemy nurkować, jedziemy.</p>
<p>Okazuje się ze moja trzy osobowa grupę prowadzić dziś będzie znany mi już wcześniej Michał Stajszczyk. Przyjeżdżamy na miejsce, dochodzimy do kamieniołomu ze zdewastowana klatka schodowa, tyrolka już rozpięta wszystko elegancko. Jest po czym sprzęt spuścić. Niektórzy nie mogą się zdecydować, jak to ujęli, na narażenie swojego życia i idą nurkować w dostępnym z auta kamieniołomie.</p>
<p>Spuszczamy się ;) ze sprzętem na dół bardzo sprawnie. Chłopaki czuwają aby sprzęt nam się rozsypał, bo z czego jest najwięcej radości? Z nieszczęścia kolegi J. Okazuje się ze jestem ostatni. Chłopaki nurkują po 40 minut, moja kolej, zasuwam wzdłuż poręczówki i kartuje. Fajna zabawa w wodzie, gdzie widzi się jeszcze tabliczkę, na której się pisze podstawiając ja pod sam nos. Na górę po schodach, już nie po tyrolce i jak mały parowozik do bazy. Wieczorem spisujemy dane z tabliczek do komputera. Wychodzi mi pętla. Nie poddaje się. Wyrzucam jeden punkt, o którym nie miałem kompletnych danych, poprawiam błednie odczytany azymut i .... udaje się - zaliczam.</p>
<p>Dzień drugi zaczynamy wykładem Pszczółka o szeroko pojętym poręczowaniu czyli: jakie węzły, jak zakładać, kiedy stosować gumki ;) kiedy ciężarki, szable, bo duch ułański w narodzie drzemie. Wydaje się nam ze już umiemy poręczowac. Po Andrzeju mówi Wiktor, pokazuje nam jak rozstawiać depozyty, gdzie po co i dlaczego.</p>
<p>Nurkujemy tym razem z Pszczółkiem. Będzie mógł sprawdzić czy go słuchaliśmy. Płyniemy wzdłuż poręczówki. Zostawiamy depozyt. Dowiązujemy się do głównej poręczówki, tworząc boczny ciąg i poręczujemy. Każdy z nas ma zastabilizować poreczowke na wszystkie możliwe sposoby i później ją po sobie zwinąć. Wszystko idzie ładnie. W pewnym momencie zauważam, że mój sekator przepadł, to co mogę nawijam na kołowrotek. To czego nie mogę odcina Pszczółek, dopływam do głównego ciągu. Odpycham się spokojnie od kamieni, podejmuję depozyt i wracam. Jestem przy konstrukcji klatki, a tu nagle jakiś dywersant zakłada mi na maskę cos dzięki czemu nic nie widzę. Jeny jestem ślepy!!!
</p>
<p>Cały czas mam jednak kontakt z poręczówka. Chłopcy dobrze to wbili do głowy. Ręka przed siebie i macam. Na szczęście ani razu nie uderzyłem w metalową konstrukcję, która w przypływie niepohamowanej agresji mogła by oddać dwa razy mocniej i zniszczyć mi kask. Wychodzę jak zwykle uśmiechnięty i parowozik do góry. Ten mały spacer ukrwił mi na tyle mózg, że zauważam swoje błędy i szybko melduje o nich Pszczółkowi, żeby nie było ze sobie nie zdaje z nich sprawy.</p>
<p>Dzień trzeci. Włodek „Spryciula” Szymanowski opowiada nam o tym jakie to jaskinie potrafią być niebezpieczne, nie to żeby nas straszył i mówił, że lepiej jest iść na piwo, ale uświadamia nas o tym, co może nas czekać, gdy natura bądź niekonsekwencja naszych działań i braku wyobraźni spłatają figla. Gdy wkracza Pszczółek i mówi, że nauczy nas radzić sobie, gdy cos pójdzie nie tak (czytaj zaplączesz się w poręczówkę), to otrząsamy się z atmosfery grozy, bo przecież damy rade .... Tak się przyglądam, co on tam robi z tymi linkami i wychodzi mi na to, że w domu ćwiczyłem cos nie tak. Słabo jest, wyćwiczone ruchy doprowadzone na sucho do perfekcji, a tu klapa. Przyglądam się uważnie i obserwuję. Chyba umiem - to pokaże praktyka.</p>
<p>Wiktor tym razem po Pszczółku opowiada nam o systemie mocowania butli po bokach. Mniej więcej mamy pojecie jak to zrobić, bo pływaliśmy ze stage’ami, ale i tu technika, jak to chłopcy nazwali europejska,  nieco rożni się od amerykańskiej, nic na plecach wszystko po bokach. Jesteśmy jak gąbki - chłoniemy. Po wykładzie biorę swój kołowrotek i przez trzy godziny, czasami przy obserwacji przez Pszczólka oceniającego poprawność i kolejność ruchów, wycinam się z różnego typu zaplątań w poręczówkę. Nie jest to łatwe, zwłaszcza, gdy cała Stajnia rży nieopodal ;).</p>
<p>Jedziemy do kamieniołomu żeby sprawdzić w praktyce czy uda nam się uratować. Nurkujemy ze Spryciulą. Od momentu zanurzenia próbuje zniszczyć moja psyche kotlując płetwami przed maska. Zastanawiam się, czy mu ich nie zdjąć ;). Poręczówka się kończy i zakładam własny punkt, rozwijam 10m, stabilizuje do kamienia, wracamy. Coś mnie nagle hamuje, to znaczy ze się zaplątałem o poręczówkę pośrednio przez gumkę i karabińczyk. Taaak, to jak to było? Zaczynam wykonywać czynności autoratownicze. W trakcie ich trwania okazuje się, że moje zadanie jest nieco utrudnione ponieważ moja poręczówka biegnie 1m od ściany i wycinam się w toni, ale nic to. Zawiązuje ostatni węzeł i tnę -  może jednak nie tak szybko. Hmm ... to chyba nie ta końcówka, ciągnę za jedna, później za druga, znowu pierwszą. Okazuje się, że odciąłbym w pośpiechu niewłaściwa, wycinam się. Jestem wolny, poręczówka ładnie napięta zachowuje ciągłość, zadowolony ze czegoś się nauczyłem wynurzam się. Ściągam płetwy i w całym szpeju przygotowuje się do następnych zajęć dla chętnych, czyli pływanie bez płetw i małymi 4l flaszeczkami po bokach. Podciągając się na rękach o kamienie bardzo sprawnie idzie mi poruszanie się w poziomie, gorzej w pionie. Wychodzę i zmieniam konfiguracje na 2x4l. Nurkuje z Michałem Gignalem na 10m i z powrotem. Mały problem stwarza mi dość wysoki, pionowy blok skalny, za którym nie ma ładnej klameczki do przytrzymania, ale daje rade. Wynurzamy się. Ja postanawiam jeszcze poćwiczyć i tak też robię.</p>
<p>Wieczorem praca z literatura oglądamy bardzo ciekawe anglo języczne pozycje książkowe i magazyny dotyczące jaskiń i rożnych projektów eksploracyjnych. Piękne. Mamy chwile spokoju. Kadra udała się na naradę. Po ciężkim dniu nie zdajemy sobie sprawy po co poszli, odpoczywamy.</p>
<p>Jest wieczór i mila atmosfera, a kadra spiskowała przeciwko nam. Wyłoniono 5 osób z puli 20, które miały zanurkować w sztolni kopalni srebra w Bystrzycy Górnej. A reszta chętnych w Nowej Wsi Kłodzkiej i Kamionkach.</p>
<p>Okazuje się ze trafiam do grupy szczęśliwców wraz z Lucyną Cieślik, Jackiem Konikowskim, Jackiem Trembowelskim, Łukaszem Lechowiczem. Jesteśmy podekscytowani i nie wierzymy ze się udało. Cała ciężka praca i przygotowania nie poszły na marne.</p>
<p>Dzień czwarty. Wraz z wyżej wspomniana grupa pięciu szczęśliwców wyruszamy pod  opieka Spryciuli i Mirka do sztolni. Na miejscu jakoś nie wiadomo jaka ma być kolejność. Po koleżeńsku jakoś nie możemy rozstrzygnąć kto wejdzie pierwszy a kto ostatni. Postanawiam przygotować losowanie: pięć karteczek z numerami przetasowanymi przez sierotkę w postaci Mirka. Chwila napięcia i rozdanie Łukasz nr1, Lucyna nr2, Jacek T. nr3, Jacek K. nr4, a ja jako autor pomysłu jako 5. Szlag mnie trafił, czekam na powrót Łukasza pod otworem. Jest,  zaczyna mi opowiadać jak to było fajnie widzieć do momentu przechodzenia światła w cień, czyli jakieś 10m albo i więcej, o tym, że woda była kryształowa. Relacja Lucyny nie była już tak kolorowa, a jak przyszedł Jacek, to się zebrałem i poszedłem na miejsce. Tam usłyszałem, że na początku było widać dno na jakichś 8m, a teraz widać tylko stemple na 1,5m <i>(co i tak było dużo – przyp. W.B.)</i>. Wychodzi Jacek i mówi, że jest fajnie na swój sposób. Nie wiem jak mam to rozumieć. Pewnie chce, abym nic mu nie zrobił, schodzę.</p>
<p>Mam na sobie zestaw 2x4, kołowrotek, 3 lampy, a to czego nie mam, to płetwy i przejrzysta woda. Pamiętając plan zalanej sztolni płynę najpierw do końca korytarza na górnym poziomie wyrobiska, starając się jak najwięcej czasu poświęcić na oglądanie ścian poprzecinanych cienkimi żyłkami koloru srebrnego. Dopływam do końca. Patrzę na komputer i już wiem, że będę czuć niedosyt. Zawracam pamiętając cały czas o zmianie automatów. Dobrze nam wpojono ten nawyk, albo podświadomie zmusza nas do tego sytuacja. Docieram do zejścia na niższy poziom, była tu tylko jedna osoba - Jacek T. To mnie pocieszało. Myślałem, że chociaż tam będę miał lepsza widoczność, ale ze względu na bardzo mała długość korytarza osad dawał się znacznie we znaki. Wynurzam się na górny poziom. Mam jeszcze dużo czasu i gazu. Płynę jeszcze raz do końca korytarza i z powrotem. Tym razem docieram do końca pod sam zawał. Analizuje wielkość dziury i postanawiam trochę się z nią dla sportu podroczyć. Puszcza -  przechodzę do połowy i wyciągam do przodu rękę ze światłem. Nie widzę końca. Może dlatego, że jest mąt, a może dlatego, że jest coś dalej. Kiedyś to sprawdzę -nie teraz. Wynurzam się. Mija mój czas. Po drodze nad zawałem zauważam zacisk. Wydaje mi się, że powinien puścić. Wynurzam się i opowiadam Mirkowi, że dziura chyba by puściła, ale jestem trochę nieśmiały bo ciasna jest i w ogóle. Usłyszałem bardzo krótko i na temat, że tam powinienem popłynąć i to sprawdzić. Tak też zrobiłem. Trochę się namęczyłem. Nie powiem, nie było łatwo, ale to, co zobaczyłem wynagrodziło wszystko co się działo od godziny. Dostałem się do malej salki z woda czystą jak kryształ. Coś, czego nie potrafię opowiedzieć, coś co zapewne czuł Łukasz, gdy wchodził jako pierwszy. Chwila pełna zastanowienia - do domu. Wynurzam się i pozuje do fotek Arnoldowi. Dzięki bardzo za pamiątki.     </p>
<p>Wychodzimy ze sztolni. Na zewnątrz pełen entuzjazmu pytam obecnych, czy byli za zaciskiem nad zawałem, nikt ze zgromadzonych wcześniej nurkujących tam nie był. Wracamy. Czekam na Wiktora może on coś wie na ten temat. Po cichu, jak dziecko łudzę się, że może udało mi się cos odkryć. Przyjeżdża granatowy opel z Wiktorem w środku. Napadam na niego i wystrzeliwuje z siebie potok słow. i pytań czy może? Niestety Wiktor B. okrutnie rozwiewa mój sen o wyeksplorowaniu salki „Laski”, mówiąc, że był już tam wcześniej. Postanawiam dążyć do tego uczucia bycia choć małym eksploratorem, bo jest ono niesamowicie piękne.</p>
<br><br>
<p>	Co mi dały warsztaty: 
Przekonanie o tym, że trzeba wysłuchać rad na temat konfiguracji, bo DIR ma się nijak do polskich jaskiń, czyli nie można być ślepym na pewne wzorce, a korzystać z najrozsądniejszej opcji, wiadomo umiejętności praktyczne, które, jeśli będą podtrzymywane, na pewno będą owocować moim bezpieczeństwem, bardzo dużo dobrej zabawy i wiarę w posiadane umiejętności, nowe kontakty, plany na przyszłość, wymianę doświadczeń. 
</p>
<p><h3>Sławek „Laska” Łaski</h3></p>
<p>*) Stajnia Kleina – grupa nurków związanych z IANTD, nurkujących zgodnie z regułami DIR.</p>


<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>