<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,6,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Podwodne jaskinie w Cassis (1)
</h1>

<p>Nurkowanie jaskiniowe to dziwna dziedzina sportu. Wymaga opanowanych do perfekcji zarówno umiejętności pokonywania jaskiń jak i technik nurkowania. Uprawianie tej dyscypliny w Polsce kojarzy się z wyczerpującym transportem ciężkiego i drogocennego sprzętu przez wypełnione błotem i ciasne korytarze. Same syfony nie są też zbyt obszerne, z lodowatą wodą o temperaturze 40 C, która mąci się prawie przy każdym poruszeniu płetwą. Powrót następuje z reguły po omacku, przy widoczności uniemożliwiającej odczyt z przyrządów. Czy tego rodzaju hobby może być przyjemne ? Nie jest to wcale pytanie retoryczne. Po prostu u nas nie ma tak naprawdę warunków do uprawiania tego sportu. 
<p>Jednak na świecie jest sporo miejsc pod ziemią, do tego zalanych wodą, które warto odwiedzić. Penetracja przestronnych, o krystalicznie czystej i ciepłej wodzie korytarzy może dostarczyć wielu wrażeń estetycznych. Przemieszczanie się w podwodnym labiryncie w stanie niemalże nieważkości ograniczają jedynie posiadane zasoby powietrza i światła. Można się poczuć jak w jakiejś fantastycznej grze komputerowej z tą tylko różnicą, że uczestniczy się w nie naprawdę. 
<p>Podobno najpiękniejsze zalane jaskinie są na kontynencie północnoamerykańskim na Jukatanie, Florydzie czy na Wyspach Bahama. Ze zrozumiałych względów trudno się tam dostać z Polski w dodatku z całym sprzętem. W Europie Mekką nurków jaskiniowych jest Francja. Znajduje się tu olbrzymia liczba zalanych jaskiń szacowana na 20 000 (dla porównania w Polsce tylko kilkanaście). Najpiękniejsze dorównują standardom amerykańskim i warto dla nich podjąć trud zorganizowania wyprawy. 
<p>Po przeanalizowaniu różnych możliwości wybraliśmy wybrzeże Morza Śródziemnego w miejscowości Cassis koło Marsylii. Są tutaj w niedalekiej odległości od siebie dwa potężne wywierzyska : Port Miou i le Bestouan o długości kilku kilometrów. Odprowadzają one słodką wodę z wnętrza lądu do morza. O wyborze tego miejsca przesądziła łatwa dostępność tych jaskiń. Można do nich dopłynąć wprost z brzegu bez użycia pontonu. 
<p>Taka była geneza wyprawy, która odbyła się w terminie 06.08 - 23.08.1997. Wzięli w niej udział : Wiktor Bolek, Michał Stajszczyk (Wrocław), Krzysztof Strama (Głogów), Norbert Ziober (Łódź) oraz osoby towarzyszące : Beata Bednarska i Aleksandra Strama. Bazę założyliśmy na kempingu Les Cigales w górnej części Cassis. Jest to jedyny kemping w tym mieście - niestety położony dosyć daleko od morza. Idąc na piechotę trzeba 30 minut, aby pokonać stromo opadające zbocze.
<p>Dzięki wcześniej nawiązanym kontaktom udało się zorganizować spotkanie z Marciem Douchetem, który przez ostatnie kilka lat prowadził intensywną działalność w tych okolicach i wyeksplorował wspomniane wcześniej jaskinie do takich imponujących rozmiarów. Umówiliśmy się z nim przed hotelem o wiele mówiącej nazwie La Pleage du Bestouan. Na spotkanie przyjechaliśmy nieco wcześniej. Niemalże w centrum miasteczka była tu maleńka, kamienista plaża wciśnięta w skalisty brzeg. Na poukładanych szczelnie obok siebie materacach i ręcznikach leżało mnóstwo obnażonych ciał. Fakt, że większość istot płci żeńskiej opalała się topless, był czymś zupełnie naturalnym. Na tej publicznej plaży były również prysznice ze słodką wodą, co stanowiło wybawienie dla każdego wynurzającego się ze słonej wody. Marc pojawił się punktualnie. Przyjechał z żoną i dwójką dzieci : 3-4 letnim chłopcem i może 7 letnią dziewczynką. Zeszliśmy na skalistą część plaży. Marc powiedział, że teraz pokaże nam otwór le Bestouan, po czym zdjął koszulkę i wskoczył do morza. Jego dzieci, nie namyślając się wiele, poszły w ślady ojca. Zaskoczeni nieco takim obrotem sprawy wskoczyliśmy do wody. Od razu zapłaciliśmy frycowe. Nadzialiśmy się na jeżowce. Marc i jego dzieci wskoczyli w klapkach bądź w plastikowych sandałkach. No cóż, płetwonurek jaskiniowy musi być ddzielny. Nie ma, że boli. Popłynęliśmy pod stromą skałę, gdzie tuż pod powierzchnią wody za załomem był niewielki otwór. Jak wyjaśnił Marc, samo wejście jest dosyć nieprzyjemne, tym bardziej że następuje tutaj mieszanie wody słodkiej i słonej. Jaskinia rozszerza się dopiero po kilkunastu metrach, gdzie w pionowej studni schodzi się na głębokość kilkunastu metrów.
<p>Ponieważ Marc miał jeszcze trochę czasu pojechaliśmy do Port Miou. Jest to jedna z najwięszych kalanek (calanque), czyli wąskich zatok o stromych skalistych brzegach głęboko wcinających się w głąb lądu. Jak sama nazwa wskazuje, jachty i najprzeróżniejsze łodzie motorowe znajdują tam schronienie. Dojechaliśmy na parking znajdujący się kilkanaście metrów nad wodą. Stąd brzeg urywał się pionową ścianą. Miejscowe dzieci skakały z tego miejsca do lazurowego morza w euforii radości. Przez chwilę myśleliśmy, że Marc też będzie chciał wejść do wody w ten sposób. Jednak my zdecydowanie skierowaliśmy się w kierunku kamiennych schodów. Otwór znajdował się po drugiej stronie kalanki i trzeba było przepłynąć wpław większy dystans - ponad 300. Musieliśmy przy tym lawirować pomiędzy zacumowanymi jachtami i motorówkami. Najgorzej było po środku kalanki, gdzie ruch był spory i aż dziw, że żadna motorówka nie zrobiła nam przedziałka na głowie. Marc oczywiście popłynął z dziećmi. Córka radziła sobie dobrze, ale synek był trochę za słaby i nie nadążął za nami, więc łapał się tatusiowi za szyję i był holowany przez większą część drogi. Wejście do jaskini wyglądało imponująco. Widoczność aż do samego dna na głębokości 15m, a tam ciemna odchłań w pionowym brzegu rodząca wyzwanie. Drogę wejścia wskazywały dodatkowo omurowane rury, króre na pewnym odcinku przechodziły przez jaskinię. W drugą stronę wychodziły głęboko w morze. Do samochów wróciliśmy bez wychodzenia na brzeg po drugiej stronie. Po spotkaniu z Marciem odniosłem wrażenie, że jest to facet będący na prawdę w stanie prowadzić eksplorację podwodnej jaskini w odległości trzech kilometrów od wejścia. 
<p>Na następny dzień zaplanowaliśmy pierwsze nurkowanie, jeszcze na powietrzu przywiezionym z kraju. 

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>