<?php

$bSubdir = true;
$sInclude = './_php/page.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,6,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Podwodne jaskinie Cassis (3)<br>
	<i>Le Bestouan</i>
</h1>

<p>Nurkowania w Port Miou wykonywaliœmy jeszcze na powietrzu przywiezionym z kraju. Teraz musieliœmy uruchomiæ sprê¿arkê. Ze wzglêdu na ha³as nie mogliœmy tego zrobiæ na kempingu. Najpierw przetoczyliœmy sprê¿arkê na placyk obok ruchliwego skrzy¿owania, ale pogoni³a nas w³aœcicielka pobliskiej posesji. Potem chcieliœmy nabijaæ butle na nieu¿ywanej drodze z dala od jakichkolwiek zabudowañ, ale wyrzuci³a nas stamt¹d stra¿ leœna. Zastawialiœmy ponoæ drogê po¿arow¹. Na domiar z³ego sprê¿arka zepsu³a siê w sposób nienaprawialny. Nikt w okolicy nie zgodzi³ siê na pod³¹czenie silnika elektrycznego. Nasz bus nie powróci³ z kraju na czas. Jednym s³owem byliœmy kompletnie zdo³owani.</p>
<p>Na szczêœcie w Cassis funkcjonowa³y kluby nurkowe, gdzie mo¿na by³o nabiæ butle. W jednym z nich uda³o siê wytargowaæ zni¿kê. By³o to i tak drogo, ale przynajmniej mo¿liwe do zaakceptowania. Za przewóz sprzêtu nad morze musieliœmy nadal p³aciæ znajomemu Polakowi z kempingu. Ostatecznie uda³o siê zorganizowaæ nurkowanie w le Bestouan.</p>
<p>Otwór jaskini znajduje siê w brzegu morza, poni¿ej poziomu wody, niedaleko pla¿y o tej samej nazwie. Tak samo jak w Port Miou jest to wywierzysko odprowadzaj¹ce znaczne iloœci s³odkiej wody do morza. Na pla¿y le Bestouan powoduje to powstawanie bardzo dziwnego zjawiska. L¿ejsza woda s³odka zalega na powierzchni tworz¹c warstwê ok. 50 cm. Poniewa¿ dopiero co wyp³ynê³a z jaskini, ma stosunkowo nisk¹ temperaturê ok. 15 oC. Poni¿ej zalega cieplejsza woda morska 25 oC. Wytwarzy³a siê w ten sposób termoklina, ale o odwrotnym gradiencie temperatur ni¿ jesteœmy do tego przyzwyczajeni w kraju.</p>
<p>Korytarz wejœciowy jaskini jest nieprzyjemny. Ciasny, w przekroju 1 x 1 m, na g³êbokoœci 1,5m. Z ca³ym delikatnym sprzêtem trzeba by³o przeciskaæ siê kilkanaœcie metrów. Na domiar z³ego widocznoœæ jest tu fatalna ze wzglêdu na mieszanie siê wody s³odkiej i s³onej. Odcinek ten koñczy siê pionow¹ studni¹, która sprowadza³a do w³aœciwego ci¹gu jaskini na g³êbokoœci 15m. Od tego miejsca jaskinia staje siê ju¿ wygodna. Œrednica korytarza waha siê  od kilku do 10 metrów. Na porêczówce nie ma ¿adnych oznaczeñ odleg³oœci. Tylko od czasu do czasu pojawiaja siê tabliczki z grubej plexi. Zawieraj¹ jednak informacjê o miejscu zakoñczenia pomiarów, np.: "Terminus Topo 2o". Dopiero po porównaniu szczegó³ów topograficznych z planem mo¿na domniemywaæ, w jakiej rzeczywiœcie odleg³oœci od otworu znajduje siê dana tabliczka.</p>
<p>Przy u¿yciu naszych dwu najwiêkszych 15 litrowych butli uda³o mi siê dop³yn¹æ za czwart¹ tabliczkê. Oznaczono j¹ napisem "Terminus Topo 3o". To miejsce by³o oddalone od otworu o ok. 400m. Dalej porêczówka zwisa³a luŸno, co mnie lekko zaniepokoi³o. Zu¿y³em ju¿ jednak 1/3 powietrza i musia³em zawróciæ. Kolejne nurkowania nale¿a³o wykonywaæ z depozytami.</p>
<p>Podczas nastêpnej akcji wykorzystaliœmy po jednej dodatkowej 8l butli. Gdy dop³yn¹³em do Terminus 3 mia³em jeszcze 20 bar do granicy 1/3. Posuwa³em siê ze szczególn¹ ostro¿noœci¹ wzd³u¿ luŸnej linki. Korytarz wznosi³ siê. Dno by³o skaliste, co zapobiega³o m¹ceniu siê wody. W pewnym momencie korytarz przechodzi³ w poziomy odcinek tworz¹c ostr¹ krawêdŸ. Tutaj zagadka luŸnej porêczówki zosta³a rozwi¹zana. Przetar³a siê na krawêdzi. Straci³em sporo czasu na uzupe³nienie brakuj¹cego fragmentu link¹ z mojego ko³owrotka. Poziomy odcinek koñczy³ siê krawêdzi¹ pionowej studni, która schodzi³a na -28m. Nad krawêdzi¹ by³a tabliczka Terminus Topo 4. Sp³yn¹³em na dó³. Tutaj studnia przechodzi³a w niski odcinek z dnem o bardzo miêkkiej glinie. W tym miejscu koñczy³ siê plan sporz¹dzony w 1992r. By³o to oko³o 440m od otworu. Pozosta³e 2 500 metrów Francuzi przep³ynêli w ci¹gu ostatnich piêciu lat. Ciekawe jak siê oni tu mieœcili ze skuterami? Powietrze osi¹gnê³o limit bezpieczeñstwa. Zawróci³em. Komputer pokazywa³ koniec czasu bezdekompresyjnego. Na szczêœcie powrót by³ z pr¹dem i szybko znalaz³em siê w studni wejœciowej. Wykona³em tu 6 minutow¹ dekompresjê wykorzystuj¹c butlê depozytow¹. Od nastêpnego nurkowania postanowiliœmy zostawiaæ tu specjaln¹ butlê na dekompresjê.</p>
<p>Wykorzystuj¹c ca³y posiadany sprzêt mogliœmy wykonaæ jeszcze nurkowanie z dwoma depozytami 8l i 10 l. Dla u³atwienia ca³ej procedury butla 10 l by³a zostawiana przez umyœlnego szerpê w odleg³oœci ok. 120 m od otworu. Ten odcinek mo¿na by³o przep³yn¹æ korzystaj¹c z 8l butli. Niestety byliœmy skazani na nape³nianie butli w klubie nurkowym. W zwi¹zku z tym ciœnienie po wp³yniêciu do jaskini by³o czasami bardzo niskie. Tym razem mieliœmy zaledwie po 175 bar w podstawowych 15-kach. Trudno by³o ponownie p³aciæ za dope³nienie do 220 bar, albo tym bardziej wymagaæ, aby mieæ odpowiednie ciœnienie na zimno, jeœli i tak ju¿ mieliœmy spor¹ zni¿kê.</p>
<p>Tym razem nurkowa³em w parze z Krzyœkiem. Nasi koledzy zostawili dla nas wczeœniej depozyty. Wp³yn¹³em do jaskini jako pierwszy. Omin¹³em depozyt Krzyœka. Odnalaz³em swoj¹ 10l butlê. Przypi¹³em j¹ do siebie, a zostawi³em ósemkê, z której dotychczas oddycha³em. Pop³yn¹³em dalej. W pewnym momencie zauwa¿y³em przed sob¹ œwiat³o. Po chwili z ciemnoœci wynurzy³ siê Krzysiek. Zbarania³em! Czy¿bym pomyli³ kierunek i p³yn¹³ z powrotem do otworu? Mo¿liwoœæ zab³¹dzenia w prostym korytarzu mo¿e wydawaæ siê czymœ absurdalnym dla kogoœ, kto nie nurkowa³ w jaskini. W historii by³o ju¿ kilka wypadków œmiertelnych, kiedy to ludzie pomylili kierunek, a w momencie gdy siê ju¿ zorientowali, zabrak³o im powietrza na powrót. Sprawdzi³em kompas. Jednak p³yn¹³em w g³¹b jaskini. Tymczasem Krzysiek uœmiechn¹³ siê do mnie przez ustnik, pokaza³ OK i pop³yn¹³ w swoj¹ stronê. Zacz¹³em intensywnie myœleæ nad zaistnia³¹ sytuacj¹. Krzysiek musia³ szybciej zmieniæ depozyt i min¹³ mnie, gdy ja by³em zajêty swoim i nie zauwa¿y³em go. A teraz rozpocz¹³ wczeœniejszy powrót. Odetchn¹³em z ulg¹. To by³o logiczne wyjaœnienie. Jeszcze nie zwariowa³em. W nurkowaniu jaskiniowym najwa¿niejsz¹ rzecz¹ jest jednak pewnoœæ podejmowanych poczynañ. Pop³yn¹³em dalej, choæ lekki stres nie opuœci³ mnie do koñca nurkowania.</p>
<p>Gdy znalaz³em siê nad studni¹ na 440 metrze, wiedzia³em, ¿e nie pop³ynê wiele dalej ni¿ poprzednim razem. Zbli¿a³em siê ju¿ do granicy 1/3. Podj¹³em jeszcze próbê przejœcia przez niski odcinek. Na szczêœcie porêczówka by³a dobrze zastabilizowana za pomoc¹ ciê¿arków. Dalej korytarz rozszerza³ siê do poprzednich rozmiarów. Na kolejnym punkcie stabilizacyjnym wisia³a tabliczka z napisem Terminus Topo 4'. By³o to oko³o 480 metrów od otworu. Rozpocz¹³em szybki powrót. Z ka¿d¹ chwil¹ komputer pokazywa³ wyd³u¿aj¹cy siê czas dekompresji. Przy tabliczce Terminus 2 wzi¹³em 10l depozyt. P³ywanie z depozytem zwiêksza opory i bezw³adnoœæ, co utrudnia utrzymywanie w³aœciwego kursu. W pewnym momencie przep³yn¹³em zbyt blisko porêczówki zastabilizowanej na œcianie. Zahaczy³a mi siê p³etwa. Nie mog³em siê ruszyæ. Szarpn¹³em raz i drugi. Puœci³o, ale spad³ mi pasek od p³etwy. Czy dalej bêdê musia³ p³yn¹æ o jednej p³etwie? W takiej sytuacji zgin¹³ Kisielow. P³yn¹³ zbyt wolno i nie zd¹¿y³ do wyjœcia. Uda³o mi siê jednak przyczepiæ p³etwê za pomoc¹ gumki zabezpieczaj¹cej. Jest to jednak doskona³y patent. Nie czu³em ró¿nicy w pracy obydwu p³etw. Lekko zestresowany nadal p³yn¹³em bardzo szybko - prawie na granicy skurczu miêœni. Na kolejnym zakrêcie poczu³em, ¿e mam zbyt du¿¹ prêdkoœæ i nie zd¹¿ê ju¿ skontrowaæ. Z ca³ym impetem wpakowa³em siê w dno. W tym miejscu by³o grz¹skie b³oto, porêczówkê zastabilizowano na du¿ym kamieniu le¿¹cym na œrodku korytarza. W momencie uderzenia natychmiast wzbi³ siê tuman mu³u ograniczaj¹c widocznoœæ do zera. Na domiar z³ego noga wesz³a mi miêdzy kamieñ a porêczowkê. Spokojnie uda³o mi siê j¹ odhaczyæ. Wyp³yn¹³em nad tuman m¹tu wypuszczaj¹c porêczówkê z rêki. Na szczêœcie powy¿ej, zgodnie z przwidywaniem, by³a ju¿ dobra widocznoœæ. Potem staraj¹c siê zachowaæ jaki taki spokój, dop³yn¹³em z obydwoma depozytami do butli dekompresyjnej.</p>
<p>Dopiero tutaj podczas 15 minutowego przystanku zrelaksowa³em siê. Opanowa³em siê nawet na tyle, ¿e postanowi³em wyp³ywaæ od razu ze wszystkimi piêcioma butlami przez ciasny korytarzyk przyotworowy. Mia³em dwie podstawowe piêtnastki, dwie ósemki i jedn¹ dziesi¹tkê. Choæ pocz¹tkowo wydawa³o siê to trudne, to posuwaj¹c siê centymetr po centymetrze wynurzy³em siê po chwili z ca³ym sprzêtem w morzu. Tutaj czeka³ ju¿ Micha³, który pomóg³ mi w holowaniu butli na pla¿ê.</p>
<p>Zastosowanie depozytów w niewielkim stopniu zwiêkszy³o nasz zasiêg penetracji. Zaledwie o 80 metrów. Z powodu braku w³asnej sprê¿arki nie mogliœmy nape³niæ butli do odpowiedniego ciœnienia. A¿eby pokonywaæ wiêksze odleg³oœci w Port Miou jak i w le Bestouan trzeba posiadaæ wiêcej sprzêtu, w tym wiêksze butle. Dotarcie do koñca bêdzie zapewne wymaga³o u¿ycia równie¿ skuterów podwodnych. Byæ mo¿e uda siê nam zrealizowaæ te zamierzenia w przysz³ym roku.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>