<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,6,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Podwodne jaskinie Cassis (3)<br>
	<i>Le Bestouan</i>
</h1>

<p>Nurkowania w Port Miou wykonywaliśmy jeszcze na powietrzu przywiezionym z kraju. Teraz musieliśmy uruchomić sprężarkę. Ze względu na hałas nie mogliśmy tego zrobić na kempingu. Najpierw przetoczyliśmy sprężarkę na placyk obok ruchliwego skrzyżowania, ale pogoniła nas właścicielka pobliskiej posesji. Potem chcieliśmy nabijać butle na nieużywanej drodze z dala od jakichkolwiek zabudowań, ale wyrzuciła nas stamtąd straż leśna. Zastawialiśmy ponoć drogę pożarową. Na domiar złego sprężarka zepsuła się w sposób nienaprawialny. Nikt w okolicy nie zgodził się na podłączenie silnika elektrycznego. Nasz bus nie powrócił z kraju na czas. Jednym słowem byliśmy kompletnie zdołowani.</p>
<p>Na szczęście w Cassis funkcjonowały kluby nurkowe, gdzie można było nabić butle. W jednym z nich udało się wytargować zniżkę. Było to i tak drogo, ale przynajmniej możliwe do zaakceptowania. Za przewóz sprzętu nad morze musieliśmy nadal płacić znajomemu Polakowi z kempingu. Ostatecznie udało się zorganizować nurkowanie w le Bestouan.</p>
<p>Otwór jaskini znajduje się w brzegu morza, poniżej poziomu wody, niedaleko plaży o tej samej nazwie. Tak samo jak w Port Miou jest to wywierzysko odprowadzające znaczne ilości słodkiej wody do morza. Na plaży le Bestouan powoduje to powstawanie bardzo dziwnego zjawiska. Lżejsza woda słodka zalega na powierzchni tworząc warstwę ok. 50 cm. Ponieważ dopiero co wypłynęła z jaskini, ma stosunkowo niską temperaturę ok. 15 oC. Poniżej zalega cieplejsza woda morska 25 oC. Wytwarzyła się w ten sposób termoklina, ale o odwrotnym gradiencie temperatur niż jesteśmy do tego przyzwyczajeni w kraju.</p>
<p>Korytarz wejściowy jaskini jest nieprzyjemny. Ciasny, w przekroju 1 x 1 m, na głębokości 1,5m. Z całym delikatnym sprzętem trzeba było przeciskać się kilkanaście metrów. Na domiar złego widoczność jest tu fatalna ze względu na mieszanie się wody słodkiej i słonej. Odcinek ten kończy się pionową studnią, która sprowadzała do właściwego ciągu jaskini na głębokości 15m. Od tego miejsca jaskinia staje się już wygodna. Średnica korytarza waha się  od kilku do 10 metrów. Na poręczówce nie ma żadnych oznaczeń odległości. Tylko od czasu do czasu pojawiaja się tabliczki z grubej plexi. Zawierają jednak informację o miejscu zakończenia pomiarów, np.: "Terminus Topo 2o". Dopiero po porównaniu szczegółów topograficznych z planem można domniemywać, w jakiej rzeczywiście odległości od otworu znajduje się dana tabliczka.</p>
<p>Przy użyciu naszych dwu największych 15 litrowych butli udało mi się dopłynąć za czwartą tabliczkę. Oznaczono ją napisem "Terminus Topo 3o". To miejsce było oddalone od otworu o ok. 400m. Dalej poręczówka zwisała luźno, co mnie lekko zaniepokoiło. Zużyłem już jednak 1/3 powietrza i musiałem zawrócić. Kolejne nurkowania należało wykonywać z depozytami.</p>
<p>Podczas następnej akcji wykorzystaliśmy po jednej dodatkowej 8l butli. Gdy dopłynąłem do Terminus 3 miałem jeszcze 20 bar do granicy 1/3. Posuwałem się ze szczególną ostrożnością wzdłuż luźnej linki. Korytarz wznosił się. Dno było skaliste, co zapobiegało mąceniu się wody. W pewnym momencie korytarz przechodził w poziomy odcinek tworząc ostrą krawędź. Tutaj zagadka luźnej poręczówki została rozwiązana. Przetarła się na krawędzi. Straciłem sporo czasu na uzupełnienie brakującego fragmentu linką z mojego kołowrotka. Poziomy odcinek kończył się krawędzią pionowej studni, która schodziła na -28m. Nad krawędzią była tabliczka Terminus Topo 4. Spłynąłem na dół. Tutaj studnia przechodziła w niski odcinek z dnem o bardzo miękkiej glinie. W tym miejscu kończył się plan sporządzony w 1992r. Było to około 440m od otworu. Pozostałe 2 500 metrów Francuzi przepłynęli w ciągu ostatnich pięciu lat. Ciekawe jak się oni tu mieścili ze skuterami? Powietrze osiągnęło limit bezpieczeństwa. Zawróciłem. Komputer pokazywał koniec czasu bezdekompresyjnego. Na szczęście powrót był z prądem i szybko znalazłem się w studni wejściowej. Wykonałem tu 6 minutową dekompresję wykorzystując butlę depozytową. Od następnego nurkowania postanowiliśmy zostawiać tu specjalną butlę na dekompresję.</p>
<p>Wykorzystując cały posiadany sprzęt mogliśmy wykonać jeszcze nurkowanie z dwoma depozytami 8l i 10 l. Dla ułatwienia całej procedury butla 10 l była zostawiana przez umyślnego szerpę w odległości ok. 120 m od otworu. Ten odcinek można było przepłynąć korzystając z 8l butli. Niestety byliśmy skazani na napełnianie butli w klubie nurkowym. W związku z tym ciśnienie po wpłynięciu do jaskini było czasami bardzo niskie. Tym razem mieliśmy zaledwie po 175 bar w podstawowych 15-kach. Trudno było ponownie płacić za dopełnienie do 220 bar, albo tym bardziej wymagać, aby mieć odpowiednie ciśnienie na zimno, jeśli i tak już mieliśmy sporą zniżkę.</p>
<p>Tym razem nurkowałem w parze z Krzyśkiem. Nasi koledzy zostawili dla nas wcześniej depozyty. Wpłynąłem do jaskini jako pierwszy. Ominąłem depozyt Krzyśka. Odnalazłem swoją 10l butlę. Przypiąłem ją do siebie, a zostawiłem ósemkę, z której dotychczas oddychałem. Popłynąłem dalej. W pewnym momencie zauważyłem przed sobą światło. Po chwili z ciemności wynurzył się Krzysiek. Zbaraniałem! Czyżbym pomylił kierunek i płynął z powrotem do otworu? Możliwość zabłądzenia w prostym korytarzu może wydawać się czymś absurdalnym dla kogoś, kto nie nurkował w jaskini. W historii było już kilka wypadków śmiertelnych, kiedy to ludzie pomylili kierunek, a w momencie gdy się już zorientowali, zabrakło im powietrza na powrót. Sprawdziłem kompas. Jednak płynąłem w głąb jaskini. Tymczasem Krzysiek uśmiechnął się do mnie przez ustnik, pokazał OK i popłynął w swoją stronę. Zacząłem intensywnie myśleć nad zaistniałą sytuacją. Krzysiek musiał szybciej zmienić depozyt i minął mnie, gdy ja byłem zajęty swoim i nie zauważyłem go. A teraz rozpoczął wcześniejszy powrót. Odetchnąłem z ulgą. To było logiczne wyjaśnienie. Jeszcze nie zwariowałem. W nurkowaniu jaskiniowym najważniejszą rzeczą jest jednak pewność podejmowanych poczynań. Popłynąłem dalej, choć lekki stres nie opuścił mnie do końca nurkowania.</p>
<p>Gdy znalazłem się nad studnią na 440 metrze, wiedziałem, że nie popłynę wiele dalej niż poprzednim razem. Zbliżałem się już do granicy 1/3. Podjąłem jeszcze próbę przejścia przez niski odcinek. Na szczęście poręczówka była dobrze zastabilizowana za pomocą ciężarków. Dalej korytarz rozszerzał się do poprzednich rozmiarów. Na kolejnym punkcie stabilizacyjnym wisiała tabliczka z napisem Terminus Topo 4'. Było to około 480 metrów od otworu. Rozpocząłem szybki powrót. Z każdą chwilą komputer pokazywał wydłużający się czas dekompresji. Przy tabliczce Terminus 2 wziąłem 10l depozyt. Pływanie z depozytem zwiększa opory i bezwładność, co utrudnia utrzymywanie właściwego kursu. W pewnym momencie przepłynąłem zbyt blisko poręczówki zastabilizowanej na ścianie. Zahaczyła mi się płetwa. Nie mogłem się ruszyć. Szarpnąłem raz i drugi. Puściło, ale spadł mi pasek od płetwy. Czy dalej będę musiał płynąć o jednej płetwie? W takiej sytuacji zginął Kisielow. Płynął zbyt wolno i nie zdążył do wyjścia. Udało mi się jednak przyczepić płetwę za pomocą gumki zabezpieczającej. Jest to jednak doskonały patent. Nie czułem różnicy w pracy obydwu płetw. Lekko zestresowany nadal płynąłem bardzo szybko - prawie na granicy skurczu mięśni. Na kolejnym zakręcie poczułem, że mam zbyt dużą prędkość i nie zdążę już skontrować. Z całym impetem wpakowałem się w dno. W tym miejscu było grząskie błoto, poręczówkę zastabilizowano na dużym kamieniu leżącym na środku korytarza. W momencie uderzenia natychmiast wzbił się tuman mułu ograniczając widoczność do zera. Na domiar złego noga weszła mi między kamień a poręczowkę. Spokojnie udało mi się ją odhaczyć. Wypłynąłem nad tuman mątu wypuszczając poręczówkę z ręki. Na szczęście powyżej, zgodnie z przwidywaniem, była już dobra widoczność. Potem starając się zachować jaki taki spokój, dopłynąłem z obydwoma depozytami do butli dekompresyjnej.</p>
<p>Dopiero tutaj podczas 15 minutowego przystanku zrelaksowałem się. Opanowałem się nawet na tyle, że postanowiłem wypływać od razu ze wszystkimi pięcioma butlami przez ciasny korytarzyk przyotworowy. Miałem dwie podstawowe piętnastki, dwie ósemki i jedną dziesiątkę. Choć początkowo wydawało się to trudne, to posuwając się centymetr po centymetrze wynurzyłem się po chwili z całym sprzętem w morzu. Tutaj czekał już Michał, który pomógł mi w holowaniu butli na plażę.</p>
<p>Zastosowanie depozytów w niewielkim stopniu zwiększyło nasz zasięg penetracji. Zaledwie o 80 metrów. Z powodu braku własnej sprężarki nie mogliśmy napełnić butli do odpowiedniego ciśnienia. Ażeby pokonywać większe odległości w Port Miou jak i w le Bestouan trzeba posiadać więcej sprzętu, w tym większe butle. Dotarcie do końca będzie zapewne wymagało użycia również skuterów podwodnych. Być może uda się nam zrealizować te zamierzenia w przyszłym roku.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>