<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,6,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Eksploracja w wywierzysku Tauz - pierwsze polskie nurkowanie rebreatherowe w jaskini
</h1>

<p>W zabitych dechami górach Transylwanii (Rumunia) są ukryte potężne wywierzyska, których głębia od wielu lat przyciąga płetwonurków. Pod koniec lat 80-tych czescy nurkowie wyeksplorowali wywierzysko Coteţul Doreştilor do -40m. W wywierzysku Tauz przepłynęli I syfon o głębokości -13m i długości 40m, a w drugim syfonie osiągnęli głębokość -70m. Natomiast w jaskini Coiba Mare w końcowym syfonie przepłynęli 130m i osiągnęli krawedź studni na głębokości -40m. W połowie lat 90-tych w tym rejonie działał zespół szwajcarsko-francuski, który eksplorował głównie Coteţul Dorestilor, gdzie osiągnięto -76m w odległości 300m od powierzchni - najgłębszy wówczas syfon w Rumunii.</p>
<p>Okazuje się, że najciekawszym miejscem do eksploracji jest system jaskiń Coiba Mare - Tauz. Z barwienia wody wynika, że woda wpadająca do końcowego syfonu w Coiba Mare wypływa w wywierzysku Tauz. Stąd też to wywierzysko stało się celem naszych kolejnych wypraw. Najpierw pojechaliśmy na wyprawę w lutym 2001. Wzieli w niej udział nurkowie Wiktor Bolek, Maciej Czykierda, Rafał Garski (Sopocki KTJ), Rafał Górecki, Norbert Ziober oraz grotołazi poruszajacy się po jaskiniach wypełnionych powietrzem : Maciej Mieszkowski, Danuta Nowak, Marcin Wójcik (pozostali SG Wrocław).</p>
<p>Pomimo nienajlepszej widoczności udało się zaporęczować znane ciągi w obydwu syfonach w Tauz. Korytarz był dostatecznie przestronny, aby się w nim poruszać. Przy dobrze zastabilizowanej poręczówce nie było problemów z ciasnościami, o których wspominali nasi poprzednicy.</p>
<p>Droga do dalszej eksploracji stała otworem. Jedyna istotna trudność polegała na braku możliwości dobrego zaporęczowania. Dno korytarza na całym odcinku pokrywał sypki żwirek. Przy ścianach było zbyt ciasno, aby szukać punktów do stabilizacji. Ciężarki również nie rozwiązywały problemu. Osuwały się pod własnym ciężarem po niestabilnym żwirku, co powodowało naciąganie poręczówki.</p>
<p>Ze względu na ilość zabranego helu, na tym wyjeździe mogliśmy przeprowadzić jeszcze jedno nurokwanie na głębokość rzędu 70-80m. Przygotowałem dwie mieszanki trimixowe oraz nitrox w butlach depozytowej i rezerwowej. Przed drugim stopniem automatów na butlach depozytowych zastosowaliśmy złączkę odcinającą (element znany również jako FCD - Freeflow Control Device). Pozwala to skrócenie do minimum operacji zostawiania butli, ponieważ nie trzeba wtedy zakręcać ani otwierać zaworu na butli. W międzyczasie okazało się, że widoczność w syfonie uległa poprawie. Podczas rozstawiania butli i poprawiania oporęczowania przed głównym atakiem, koledzy skorzystali z okazji i wykonali głębokie nurkowania na powietrzu. Rafał Górecki zanurzył się na -66m, a Maciek Czykierda i Rafał Garski na -60m.</p>
<p>Podczas głównego ataku dowiązałem linkę do ostatniego punktu i zacząłem zanurzać się głębiej. Jednak szybko wyłoniło się przede mną zwężenie korytarza. Na stropie uformował się swojego rodzaju garb, który biegł przez całą szerokość korytarza. Przekrój był w tym miejscu niski ale szeroki. Byłem na -74- -75m. Dostępna przestrzeń stwarzała możliwość przepłynięcia. Obróciłem się płetwami w dół i przeszedłem przez zwężenie bez problemów. Dalej korytarz opadał łagodnie w dół. Głębokość przyrastała powoli. Po lewej stronie pojawił się w stropie kolejny garb. Jednak w prawo otwierała się przestrzeń. Na dnie ukształtowało się coś w rodzaju wydmy. Przepłynąłem w prawo przez grań uformowaną ze żwiru. W tym momencie uświadomiłem sobie, że ta czynność możę zmienić ułożenie poręczówki w przewężeniu. Nie miałem wystarczającej ilości ciężarków ani czasu, by ten odcinek dobrze zaporęczować. Wykorzystałem już prawie całą mieszankę przeznaczoną na penetrację. Zbliżyłem się do granicy 80 metrów. Komputer wskazał maksymalną głębokość -79.4m. Zastabilizowałem ciężarek i ropocząłem powrót. Czekało mnie jeszcze przejście przez przewężenie. Położyłem się ostrożnie na żwirku i delikatnymi ruchami przesuwałem się do góry. Przeszedłem bez problemu. Lekko tylko dotknąłem butlami stropu. Dekompresję rozpocząłem na -21m. Musiałem jeszcze spędzić w wodzie godzinę zanim mogłem wreszcie wynurzyć się.</p>
<p>Perspektywy eksploracji w wywierzysku Tauz rysowały się bardzo dobrze. Syfon okazał się na tyle przestronny, ze można się w nim poruszać bez większych problemów nawet przy słabej widoczności. Problem, który pozostawał do rozwiązania, to solidne zastabilizowanie poręczówki w miejscu, gdzie korytarz jest najwyższy.</p>
<p>Kolejną wyprawę zorganizowaliśmy w sierpniu 2001. Wzięli w niej udział nurkowie: Wiktor Bolek - kierownik, Maciej Czykierda, Grzegorz Dominik (TDI), Mirosław Kopertowski, Ireneusz Królikowski (TDI), Michał Stajszczyk, Andrzej Szerszeń (Speleoklub Warszawski), Włodzimierz Szymanowski (pozostali SG Wrosław) oraz grotołazi poruszający się po suchych jaskiniach.</p>
<p>Tym razem działalność postanowiliśmy rozpocząć od wymiany poręczówki. Do jej stabilizowania w piaskowym korytarzu postanowiliśmy użyć "piaskowych szabel" - nazwanych poprzez analogię do stosowanych w alpinizmie szabel śnieżnych. Były to ok. 30 cm długości aluminiowe kątowniki, które zamierzaliśmy wbijać w dno młotkiem. W praktyce okazało się jednak, że piasek był na tyle luźny, że szable wchodziły na całą długość wpychane ręcznie. Co gorsza równie łatwo wychodziły. Dopiero szable o długości 50 cm były dobrze osadzone. W ten sposób wymieniliśmy oporęczowanie do -75m w odległości 190m od powierzchni. Okazało się przy tym, że na -74m nie ma żadnego zacisku! Przy pomocy szabel poręczówkę poprowadziliśmy precyzyjnie w najszerszym miejscu, tzn. po prawej stronie korytarza. Do -50m (160m od powierzchni) pochylnia opadała na północ. Jednak od tego miejsca korytarz zaczynał skręcać szerokim łukiem w lewo (na zachód). Na -75m oś korytarza była już skierowana na zachód. W sytuacji, gdy linka była zastabilizowana z ciężarków zagłębiających się w piasku pod wpływem siły ciężkości, poręczówka naciągała się i przesuwała w lewo - w najciaśniejszy punkt w przekroju korytarza. Stąd też poprzednim razem eksploracja odbywała się po lewej stronie, gdzie na -74m pojawił się zacisk. Reżim nurkowania trimixowego nie pozostawił wóczas czasu na sprawdzenie prawej strony korytarza. Stało się to możliwe dopiero podczas tej wyprawy, gdyż od początku używaliśmy solidnych punktów do stabilizacji. Poniżej -50m stara poręczówka obciążona jeszcze ciężarkami tak głęboko zagrzebała się w piasek, że nie byliśmy już w stanie jej stamtąd wyciągnąć.</p>
<p>Po takim przygotowaniu zaplanowałem trimixowy atak na głębokość rzędu -90m. Koledzy rozstawili depozyty z powietrzem i nitroxem w niszy na -14m oraz z tlenem na -6m. W pierwszym syfonie i na początku drugiego oddychałem powietrzem z butli depozytowej, którą zostawiłem na -30m. Na -75m podjąłem kołowrotek zostawiany tam podczas przygotowań. Płynąłem wzdłuż prawej ściany. Po lewej stronie strop obniżał się i korytarz stawał się niższy. Dalej eksploracja potoczyła się szybko. Ani się obejrzałem, a już minąłem głębokość -80m. Po paru metrach minąłem pionową krawędź na prawej ścianie i wypadłem do poziomego korytarza. Osiadłem powoli na piaszczystym dnie i starałem się jak najlepiej zrozumieć zmianę konfiguracji terenu. Pochylnia skończyła się na -82m, gdzie łączyła się z poziomym korytarzem biegnącym na pólnoc. To dawało ten zakręt w prawo wokół pionowej krawędzi, którą widziałem wcześniej. Zastabilizowałem poręczówkę na dnie z dwu szabel i popłynąłem na północ przy lewej ścianie. Korytarz sprawiał wrażenie wysokiego - jak oceniłem - na co najmniej 2 metry. Dno było pokryte ławicami piasku. Od czasu do czasu pojawiały się fragmenty gałązek czy kory drzew. W pewnym momencie natknąłem się nawet na spory korzeń z kawałkiem pnia. Głębokość wahała się od -83m do -84m. Po chwili zobaczyłem większe zagłębienie w piasku, gdzie przy dnie komputer dał odczyt -85m. Na poręczówce minąłem marker 250m. Upłynęła właśnie 15 minuta nurkowania. Aby zmieścić się w planie musiałem wrócić na -30m najpóźniej w 26 minucie. Aby nie ryzykować przedłużenia czasu postanowiłem zakończyć eksplorację. Zastabilizowałem poręczówkę z dwu kolejnych szabli i rozpocząłem powrót. Na zakręcie wprowadzającym na pochylnię linka ocierała się o krawędź. Przy pomocy ostatniej szabli odciągnąłem ją od ostrej krawędzi. W drodze powrotnej zrobiłem jeszcze kilka pomiarów głębokości i azymutu. Na -30m byłem po 24'. Na powierzchnię wynurzyłem się po półtoragodzinnej dekompresji.</p>
<p>Odległość w linii prostej między końcowym syfonem w Coiba Mare i Tauz wynosi 2500m. Pokonanie takiej odległości przy głębokości -85m jest złożonym problemem, przede wszystkim ze względu na ilość potrzebnych gazów i czas dekompresji. Przepłynięcie takiego dystansu w aparatach o obiegu otwartytm na pewno będzie bardzo czasochłonne. Wobec tego należy rozważyć możliwość eksploracji w aparatach o obiegu zamkniętym.</p>
<p>W celu przetestowania nowej techniki przeprowadziliśmy nurkowania na rebreatherze Buddy Inspiration. Grzegorz Dominik został pierwszym Polakiem, który zanurkował w jaskini na tego typu urządzeniu. W Tauz przepłynął 130m osiągając głebokość -30m w II syfonie, a w wywierzysku Coteţul Dobreştilor 150m przepływając przez pierwsze przegięcie na -50m. Wnioski wynikające z tych nurkowań są bardzo zachęcające. Jednak dopracowania będzie wymagał sposób zwiększenia bezpieczeństwa na wypadek awarii urządzenia w warunkach jaskiniowych.</p>
<p>Jak do tej pory poznaliśmy jedynie mały fragment systemu łączącego Coiba Mare z Tauz. Obecność dużych fragmentów drzew świadczy o tym, że połączenie musi być przestronne i dostępne na całej długości dla człowieka. To wszystko czyni eksplorację w tym miejscu bardzo ekscytującą.</p>

<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>