<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,6,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Nurkowanie w Mokrej Dziurze wrzesień 2000
</h1>

<p>W dniach 23-24 września 2000 została zorganizowana akcja nurkowa w jaskini Mokra Dziura w Dolinie Jaworzyńskiej w Tatrach Wysokich. Wzięło w niej udział dwu nurków: Wiktor Bolek i Norbert Ziober (SG Wrocław). Grupa pomagająca w transporcie składała się z następujących osób: Stano Pavlarčik- kierownik, Igor Michlich, Peter Knaus, Jan Tencer, Jozef Leščak, Jan Zibura, Luboš Vnenčak.</p>
<p>Poprzednie nurkowanie zostało przeprowadzone w marcu 2000. Udało się wówczas założyć 80m poręczówki poczynając od dna studni wejściowej (-15m). Dalszą penetrację uniemożliwiła wówczas bardzo zimna woda (10C), która powodowała bardzo szybkie zamarzanie automatów.</p>
<p>Podczas nurkowania we wrześniu należało oczekiwać, że woda w syfonie będzie cieplejsza. Jak wskazują dotychczasowe obserwacje, część wody do syfonu dostaje się z potoku płynącego dnem doliny. Te przypuszczenia potwierdziły się. Woda miała temperaturę 40C w dniu 23.09 oraz 30C w dniu 24.09. Spadek temperatury był wynikiem nocnego przymrozku.</p>
<p>W dniu 23.09 pierwsze nurkowanie wykonał Norbert z dwoma butlami po 8l. Dopłynął na 80-ty metr - na koniec poręczówki zostawionej tu przez nas w marcu. Dowiązał poręczówkę z nowego kołowrotka. Niestety nie był w stanie prawidłowo odblokować korbki i linka wysuwała się z kołowrotka z bardzo dużymi oporami. Spowodowało to zerwanie poręczówki z wcześniej zastabilizowanych punktów. Po rozwinięciu ok. 10m Norbert stwierdził, że nie da się tak płynąć dalej. Zostawił kołowrotek i wrócił.</p>
<p>Kolejne nurkowanie tego samego dnia wykonał niżej podpisany. Dopływając do 80-tego metra zauważyłem, że poręczówka jest mocno naciągnięta i wchodzi w ciasną część korytarza na zakręcie w prawo. Kołowrotek wziąłem na 90-tym metrze. Odblokowałem korbkę i popłynąłem dalej. W przeciwieństwie do wcześniejszych relacji (Kucharovič), dno nie było niestety wolne od osadów. Zwłaszcza po lewej stronie korytarza gromadził się piasek zmieszany z drobinami najprawdopodobniej pochodzenia organicznego. Po prawej stronie dno stanowiła czysta, lita skała. W odległości 100-110m z dna wystawał skalny garb, który w zasadzie rozdzielał korytarz na dwie części. Po lewej strop był bardzo nisko nad dnem pokrytym osadami. Natomiast po prawej było przestronnie i bez żadnych osadów. Było to doskonałe miejsce do zastabilizowania poręczówki. W tym miejscu zastabilizowali swoją poręczówkę moi poprzednicy. Na nieszczęście prąd wody musiał ją zerwać z następnych punktów, tak że zwoje luźnej linki oplątywały ten cały garb i lekko falowały na prądzie. Zaplątanie się w coś takiego mogłoby się skończyć tragicznie. Nie mając drugiego kołowrotka, na który mógłbym nawinąć starą poręczówkę, nie mogłem posprzątać tego miejsca. Nową poręczówkę zastabilizowałem jednak tak, aby w żadnym punkcie nie krzyżowała się ze starą. Popłynąłem dalej. Lewa strona korytarza w dalszym ciągu była pokryta osadami, a dno po prawej (bardziej strome) było lite. Korytarz wznosił się do góry. Nie było żadnych punktów, gdzie mógłbym zastabilizować poręczówkę. Wykopałem więc z piasku granitowy otoczak, który przymocowałem za pomocą gumki do poręczówki. W odległości 150m osiągnąłem limit posiadanego powietrza i zawróciłem.</p>
<p>W dniu 24.09 pierwsze nurkowanie również wykonał Norbert. Głównym celem tego nurkowania było uporządkowanie nowej poręczówki na odcinku między 60 a 100 metrem oraz zwinięcie starej poręczówki. Norbert planował najpierw popłynąć na przodek, a porządki zrobić w drodze powrotnej. Gdy dopłynął za garb na 120-130 metr zamarzł mu jeden z automatów. Z butli uciekało mu błyskawicznie powietrze. Nie namyślając się wiele Norbert rozpoczął natychmiastowy powrót. Jednak przepływając w pośpiechu koła garbu popełnił błąd. Chciał go minąć po niskiej stronie, gdzie dno było pokryte osadami i gdzie znajdowała się większość zwojów starej poręczówki. Płynąc z uciekającym z butli powietrzem, już w lekkiej panice, zaplątał się w luźne zwoje starej linki. Uderzył w dno, zmącił kompletnie wodę, woda zaczęła zalewać mu maskę. Na szczęście opanował sytuację. Przedmuchał maskę. Prąd wody uniósł wzburzone osady i poprawił nieco widoczność. Przy pomocy nieocenionego, ogrodniczego sekatorka wyciął się z linki. Na szczęście zaplątał się tylko w starą poręczówkę. Po wycięciu się nowa linka pozostała na swoim miejscu. Dzięki niej mógł bezpiecznie wrócić na powierzchnię z jedną butlą całkowicie pustą.</p>
<p>Rozpoczynając kolejne nurkowanie spodziewałem się totalnego chaosu pod wodą. I nie omyliłem się. Do 50m, gdzie zostawiłem butlę depozytową, wszystko jeszcze było dobrze. Jednak dalej nasza poręczówka była jeszcze bardziej niż poprzednio wciśnięta w ciasne miejsce na zakręcie. Ponadto wielokrotnie krzyżowała się z luźnymi zwojami starej poręczówki. Na 110m okolice garbu wyglądały jak pobojowisko. Na szczęście nowa poręczówka była nienaruszona i w dostatecznej odległości od zdradliwych zwojów starej poręczówki. Popłynąłem dalej. Miałem zestaw 2x10l, który powinien pozwolić na o wiele dalszą penetrację niż poprzednio. Na 150m podjąłem pozostawiony tam poprzednio kołowrotek. Korytarz wznosił się do góry aż do -17m w odległości 180m. Tu dno wypłaszczyło się. Nie było żadnych śladów poręczówki po poprzednikach. Ku mojemu zdumieniu korytarz szedł dalej w dół i nieco się zwężał. Było to w jawnej sprzeczności z tym co oglądałem na rysunku. Dopiero po pewnej chwili dostrzegłem po prawej stromą pochylnię idącą do góry. Zacząłem szukać punktu do zastabilizowania poręczówki. Zajęło mi to 2-3 minuty. Po czym popłynąłem do góry. Korytarz był przestronny. Po lewej zwężał się jednak i stawał się bardzo niski z dnem porytym osadami. Najważniejsze było, aby nie dopuścić, by poręczówka została wciągnięta w to miejsce. Płynąc cały czas po prawej stronie wynurzyłem się do -10m. Pochylnia kończyła się tu ciasną, niską szczeliną w dodatku pokrytą organicznymi osadami. Można jednak było płynąć dalej w lewo. Opłynąłem obły filar. Znalazłem się w salce, która wieńczyła lewą część pochylni. Z kołowrotka odwinął się właśnie marker oznaczający 200m. Znalazłem odpowiednie otoczaki do zastabilizowania poręczówki. Na tym postanowiłem zakończyć penetrację. Nie zauważyłem żadnych śladów poręczowania przez poprzedników. Z tej salki można byłoby płynąć jeszcze trochę do góry, ale tam przestrzeń zwężała się i nie wyglądało to zachęcająco. O wiele lepiej wyglądały perspektywy eksploracji w poziomie, gdzie co prawda, korytarz stawał się węższy niż poprzednio i miał nieregularny charakter, to jednak widać było kilka metrów przestrzeni. Po stwierdzeniu tych faktów rozpocząłem powrót. Woda była częściowo zmącona. Zwłaszcza organiczne drobiny wzniesione z dna pogarszały widoczność. Koło garbu przepłynąłem z właściwej strony. Dalej było gorzej. Źle ułożona poręczówka powodowała, że musiałem cały czas szorować butlami po stropie. Widoczność poprawiła się dopiero przed studnią wejściową. Wynurzyłem się bez konieczności wykonywania dekompresji.</p>
<p>Podsumowując, podczas czterech przeprowadzonych nurkowań udało się rozciągnąć poręczówkę do 200 metra. Ponieważ poprzedni zespół relacjonował przepłynięcie 195m, to można pokusić się o stwierdzenie, że odkryto 5-10 metrów nowego terenu. Przy tym stwierdzeniu należy uwzględnić, że wstępna część studni wejściowej nie wchodzi do tego 200m odcinka poręczówki, oraz to, że teraz poręczówka mogła zostać poprowadzona inaczej - na pewno było więcej razy stabilizowana. Ponadto od garbu nie natknąłem się na żadne ślady poprzedniego poręczowania, co utrudnia porównanie osiągniętych punktów. Maksymalna głębokość odczytana z komputerów Aladin wynosiła 31.5m.</p>
<p>Dalsza eksploracja będzie jednak wymagała dokładnego uporządkowania poręczówki na pierwszym odcinku, tak aby w razie jakiejkolwiek stresowej sytuacji poręczówka wskazywała bezpieczny powrót na powierzchnię.</p>


<h3 align=right>Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>