<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,7,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Jochen Hasenmayer - mistrz z Niemiec
</h1>

<p>Przez ponad dwadzieścia lat scena europejskiego nurkowania jaskiniowego była zdominowana przez Jochena Hasenmayera, który nie tylko osiągał rekordowe wyniki, ale i wytyczał nowe kierunki rozwoju tej dyscypliny. Zyskał przez to szacunek w całej międzynarodowej społeczności płetwonurków. Mimo to jednak pozostał postacią nieco tajemniczą. Całą swą działalność prowadził samodzielnie i większość szczegółów zachowywał dla siebie. Publikował stosunkowo niewiele na temat swoich dokonań. Pracując spokojnie w południowych Niemczech zdołał ulepszyć niemal każdy aspekt nurkowania w jaskiniach. Zawsze wykazywał znakomity zmysł praktyczny przy konstruowaniu sprzętu. Rozwiązywał nie tylko większość istniejących problemów, ale również wskazywał na istnienie możliwości, stwarzających zupełnie nowe perspektywy. 
<p>Nurkując w jaskiniach przez ponad dwadzieścia lat poznał fizjologię człowieka związaną z głębokim nurkowaniem. Do roku 1980 udało mu się wykorzystać tę wiedzę do stworzenia odpowiednich programów komputerowych, co pozwalało mu obliczać dekompresję przy złożonych profilach nurkowania. Inny projekt był jeszcze bardziej futurystyczny. Hasenmayer doszedł do wniosku, że przyszłość nurkowania w jaskiniach leży w aparatach o obiegu zamkniętym, w których można kontrolować skład podawanego gazu. Zaowocowało to w 1980r. konstrukcją aparatu o nazwie Speleo- Twin Rebreather (STR 80). Składał się on z dwu odzielnych aparatów, z których każdy wystarczał na 24 godziny niezależnie od głębokości. W każdym z nich umieszczono czujnik zawartości tlenu, którego podawanie było kontrolowane za pomocą komputera. W przypadku awarii elektroniki, aparat można było używać w układzie półotwartym. Na wypadek całkowitej awarii była przewidziana dodatkowa butla ze zwykłym automatem działającym w obiegu otwartym. Należy przy tym zauważyć, że inne tego typu konstrukcje (nawet profesjonalne, wojskowe) pojawiły się dopiero w drugiej połowie lat osiemdziesiątych. 
<p>Swoją karierę Hasenmayer rozpoczął w 1958 w wieku czternastu lat nurkując w Falkenstein Hohle, położonej pomiędzy Stuttgartem a Ulm w Niemczech. W tym celu zrobił sobie kombinezon z podgumowanych prześcieradeł. Nie miał w nim zamka, tak że przed każdym nurkowaniem uszczelniał ten kombinezon na sobie, a później rozcinał się.
<p>Do jego największych osiągnięć należy zaliczyć nurkowania w Fontaine de Vaucluse w 1981 i 1983. Jochenowi nie udało się uzyskać oficjalnego pozwolenia, ponieważ w tym samym czasie do nurkowania przygotowywał się francuski płetwonurek Claude Touloumdjian wspierany przez znaną firmę COMEX. Niezrażony tym Hasenmayer wykonał w tajemnicy nurkowanie, wspierany tylko przez swoją żonę. Osiągnął głębokość -143m podczas zanurzenia trwającego pięć i pół godziny, co było wówczas światowym rekordem głębokości. Kilka tygodni później Touloumdjian wykonał zanurzenie trwające siedem godzin. Schodząc w dół olbrzymią pionową studnią znalazł poręczówkę Hasenmayera zawiązaną na 143m i następnie zszedł jeszcze na 153m poniżej powierzchni. Te wydarzenia spowodowały spore zaiteresowanie mass-mediów. Przedstawiano je jako pojedynek pomiędzy Francuzami a Niemcami. 
<p>Następne nurkowanie Jochen wykonał dwa lata później w 1983. W chwili gdy wchodził do wody jego sprzęt ważył 400 kg, składało się na niego m. in.: dziewięć dwudziestolitrowych butli z odpowiednimi mieszankami i podwodną kamerę do zarejestrowania wydarzenia. Wziął również żywność w odpowiedniej butelce ze smoczkiem, którtą trzymał w kasku. Zanurzanie się z taką ilością sprzętu było stosunkowo wolne, po 45 minutach od opuszczenia bazy osiągnął oszałamiającą głębokość -205m. Po upływie dalszych dziewięciu godzin szczęśliwie wynurzył się, wykonując w tym czasie wymaganą dekompresję. Dokładny skład użytych mieszanek nie został ujawniony. Nurkowanie nie wywołało u niego żadnych efektów chorobowych. Kolejny raz granice ludzkiej aktywności zostały przesunięte jeszcze dalej. 
<p>Oprócz tego Jochen prowadził działalność w syfonach o długościach przekraczających kilometr, zwłaszcza w Emergence du Ressel we Francji (1860) i w Blautopfie (1250) w rodzinnych Niemczech. Z jego bogatej działalności warto jeszcze wspomnieć o osiągnieciach na terenie nieco bliższym nam, Polakom, a mianowicie w masywie Hocher Goll w Austrii. W tym rejonie Polacy eksplorowali szereg głębokich jaskiń, takich jak : Jubileuszowa, Mondhohle, czy ostatnio odkryte jaskinie Wietrzna i Skrzata, dzięki działalności wypraw katowickich. Hasenmayer nurkował w wywierzysku odwadniającm ten masyw (Gollinger Wasserfall) w 1973r. Osiągnął głębokość 50m w odległości stukilkudziesięciu metrów od jeziorka. Problem jest nadal otwarty. Przestronny korytarz biegnie dalej na zachód w głąb masywu. Ewentualne połączenie Gollinger Wasserfall z jedną z wcześniej wymienionych jaskiń może dać rekordowy wynik.
<p>W 1989 kariera nurkowa Jochena Hasenmayera została przerwana. Podczas nurkowania dla TV w Wolfgangsee na zachód od Salzburga, w wyniku awarii głębokościomierza Jochen wykonał przystanek dekompresyjny na 25 m zamiast na 40m, co natychmiast sparaliżowało mu nogi, jednak zdołał się wynurzyć. Umieszczono go w komorze dekompresyjnej, dzięki czemu mu chwilowo odzyskal władzę w nogach. Jednak w wyniku dalszych błędów popełnionych podczas leczenia dekompresyjnego został na trwałe sparaliżowany od pasa w dół. Ma jednak nadzieję nadal nurkować. Obecnie pisze autobiografię, która na pewno wyjaśni wiele fascynujących szczegółów z jego niebywałej solowej kariery podwodnego odkrywcy. 

<h3 align=right>Tłumaczenie - Wiktor Bolek</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>