<?php

$bSubdir = true;
$sInclude = './_php/page_utf8.php';
if($bSubdir == true)
	$sInclude = '.'.$sInclude;
@include($sInclude);

	renderHead($bSubdir);
	renderMenu($bSubdir,7,true);
	renderGallery(true,false);
	renderCentral(true);
?>
<!--============================= CONTENTS START ==========================================-->
<h1>
	Wypadek w Grocie Scaletta na Przylądku Iacco (Capo Palinuro)
</h1>

<p>Dnia 10 .09.1996 o 17.30 trzech płetwonurków z Polski : Grzegorz Sosinka, Rafał Spyrka i Witold Olszowski, przebywający już od miesiąca we Włoszech na wyprawie, wpływają do jaskini Scaletta. Jest to dla nich trzecia zanurzenie tego dnia (wynika to z profilu nurkowania odczytanego później z komputera). Prawdopodobnie wszyscy mają mało powietrza w butlach. Nie posiadają ze sobą kołowrotka z poręczówką i mają tylko dwie latarki na trzech. Do tego tylko Witold ma komputer. Jaskinia schodzi na -43m ciasnym korytarzem, który u podstawy rozszerza się tworząc małą salkę, w której zbiegają się inne korytarze mniej więcej równoległe do studni wejściowej. Cała trójka, po zejściu na -35m, prawdopodobnie nie może znaleźć drogi powrotnej w tym małym labiryncie i szybko kończy się im powietrze. Ich koledzy na powierzchni po daremnym oczekiwaniu, wracają do Palinuro aby zaalarmować kapitanat portu. Od tej pory zaczynają się długie i bolesne poszukiwania ciał przez nurków z miejscowego klubu "Pesciolino" i VVFF (strażacy).</p>

<p align=center>
	<a href="./img/scaletta.gif" target="_new">
		<img src="./img/scaletta_small.gif" alt="Orientacyjny przekrój przez Grotta Scaletta" height=350 width=239></a><br>
	<i>Orientacyjny przekrój przez Grotta Scaletta</i>
</p>

<p>ANSA natychmiast wysyła informację o wypadku. Grupa ratownictwa jaskiniowego  i Komisja Nurkowania Jaskiniowego powiadamia, że jest gotowa w razie potrzeby do wzięcia udziału w akcji. Ale z Palinuro nie dochodzą żadne nowe sygnały i sprawa jest początkowo odłożona ad acta.</p>
<p>Natomiast 16.09 grupa CNSAS (Corpo Nazionale Soccerso Alpine e Speleologico) przyjeżdża, po otrzymaniu informacji od VVFF z Salerno, aby wydobyć ostatnie ciało - Witolda, którego zarówno miejscowi płetwonurkowie jak i strażacy nie mogą odnaleźć. W istocie, od chwili wypadku każdego dnia grupy nurków VVFF  wraz z nurkami z "Pesciolino" schodzą pod wodę i wydobywają dwa ciała, lecz później przez brzydką pogodę i mała wprawę w nurkowaniu jaskiniowym poszukiwania utknęły w martwym punkcie. W następnych dniach przyjeżdżają : niżej podpisany -  delegat V grupy i Paolo Verico - odpowiedzialny w kraju za ratownictwo jaskiniowe. W wyczerpujących rozmowach w Salerno z Prefekturą, VVFF i Obraną Cywilną, negocjują możliwość odbycia długiej podróży  i rozlokowania się w Palinuro  nie tylko na własny koszt.  (Oczywiście Polacy nie byli członkami CAI). Wszystko co udaję się uzyskać, to gwarancje pokrycia wydatków ze strony Obrony Cywilnej. Natomiast rozmowa z burmistrzem Centola (do którego należy Palinuro) kończy się optymistycznie - jesteśmy gośćmi komuny.</p>
<p>Zapada decyzja o wyjeździe dopiero 20.09 po otrzymaniu  od VVFF potwierdzenia, że nie wydobyto ostatniego ciała. Ta informacja jest potwierdzona faxem z prefektury, co jest niezbędne do pokrycia wydatków przez Obronę Cywilną. Wiadomości z Palinuro są sprzeczne i niedokładne. 20.09 brak wiadomości ze strony VVFF aż do 14.00, kiedy to decyduję się zadzwonić po informacje. Oczywiście w Salerno nikt nic nie wie i po faxie nie ma żadnego śladu. Domyślamy się, że to koniec interwencji, ale ponownie nas wzywają i VVFF potwierdza prośbę o pomoc.</p>
<p>21.09 wyjeżdżają Luigi Casati, Massimo Bollati i Claudio Guidici z komisji Nurkowania Jaskiniowego oraz Massimiliano Re i Bernardino Bocchia jako pomoc i niżej podpisany jako odpowiedzialny za strefę. Przyjeżdżamy na miejsce o 17.00. Cały czas obawiamy się, że podróżowaliśmy na próżno. Jednak na breefingu w kapitanacie informują nas, że ciało jest jeszcze w wodzie, zaklinowane na -20 w bocznej galerii, gdzie prawdopodobnie płetwonurek zginął podczas ostatniej desperackiej próby wyjścia. Spotkanie z nurkami VVFF jest z początku trochę burzliwe ("Kto was tu wzywał?") - zapewne dlatego, że grupy wymieniające się w Palinuro nie miały dobrego połączenia z Salerno i (być może) nie wiedziały zbyt wiele o inicjatywach podejmowanych przez zwierzchników.  W każdym razie dwuznaczności zostają szybko wyjaśnione i staje się jasne, że grupy CNSAS będą działały pod wodą całkowicie niezależnie. Wieczorem przybywa sprzęt i uzgadniamy program na dzień następny.</p>
<p>22.09 o 08.00 rano jesteśmy w porcie oczekując na motorówkę SAR, która zabierze nas i nurków VVFF na miejsce wypadku. Łódź przypływa o 09.30, lecz trzeba jeszcze czekać na helikopter strażaków, który przez wszystkie dni czekał w pogotowiu, aby ewentualnie przetransportować nurków do komory dekompresyjnej w Salerno. W końcu o 11.00 Guidici, Casati, Bollati mogą się zanurzyć w asyście 2 nurków z VVFF, którzy pozostaną na -10m - na zewnątrz jaskini.</p>
<p>Ciało jest zaklinowane na około -20m. Zaawansowany stan rozkładu sprawia, że zaraz po uwolnieniu wypływa niespodziewanie do korytarzyka na 5/6m (nieopisany na planie). Po obciążeniu balastem zostaje ściągnięte ponownie na -20, skąd ma być przez okienko wyciągnięte na powierzchnię. Lecz pęknięcie linki sprawia, że ciało znowu unosi się do górnej studni - prawie do samej powierzchni. Ponieważ nie da się wyjść z tej strony i uczestnikom akcji zostało już mało powietrza w butlach akcja zostaje przerwana o 12.30 i nurkowie wycofują się by napełnić butle.</p>
<p>Po południu o 17.00 kolejna próba przy użyciu łodzi, która jest bardziej stabilna od motorówki. Lecz ciała nie ma w tym samym miejscu, a do tego morze zerwało wszystkie linki. Wzburzone morze czyni wejście do jaskini bardzo trudnym i zapada decyzja o powrocie. W poniedziałek rano próba wypłynięcia, lecz morze jest jeszcze bardziej wzburzone i niemożliwe jest nawet wyjście z portu. Zapada decyzja o zawieszeniu operacji do 26.09, gdy według wojskowych prognoz pogoda powinna być lepsza.</p>
<p>W czwartek znowu denerwujące kontakty z kapitanatem portu, VVFF, Obroną Cywilną. Nurkowie ze straży kilka razy nurkowali i udało im się zlokalizować jedynie niektóre części ciała i sprzętu.</p>
<p>Wyjeżdżamy w nocy. O świcie jesteśmy w Palinuro - wszyscy oprócz Bollatiego zastąpionego przez Luigiego Liveraniego. W piątek odbywają dwa nurkowania grupy z CNSAS. Pierwsze o 11.00 i drugie o 16.30 podczas których są odzyskane : butle, balast, części sprzętu i komputer. Komputer jeszcze działa. Podłączony do komputera w kapitanacie odtwarza ostatnie nurkowanie Witolda. Po trupie niestety żadnego śladu. Morze nie pozwala na wejście do górnej studni, ale ślady pozwalają domyślać się, że jest właśnie w tej części. Następnego dnia o 08.00 korzystając ze spokojnego morza jesteśmy ponownie na przeciw Punto Iacco. Tym razem Guidici i Re spróbują się dostać do jaskini od strony powietrznej tak, aby dojść do szczytu studni górnej. Natomiast Casati i Liverani spróbują dostać się od dołu. Próba udaje się. Ciało zostaje odnalezione w malutkiej komorze nad studnią. Stan ciała jest niewyobrażalny. Możliwe jest wydobycie tylko jego części, ponieważ nie ma dodatkowego niezbędnego sprzętu.  Powrót do portu o 9.30. Morze jeszcze raz nie pozwala na wyjście popołudniowe.</p>
<p>Po długim breefingu w kapitanacie, upadli na duchu, decydujemy się na ponowną próbę o świcie następnego dnia. Tymczasem Germani i Guidici wracają do Rzymu do zwykłych zajęć. 29.09 jak zwykle o świcie Re i Bocchio wchodzą ponownie do części powietrznej jaskini lecz nie udaje się im wydobyć ciała z korytarza, w którym jest zaklinowane. Dwóch pozostałych płetwonurków nie znajduje nic. Wydaje się, że to przeznaczenie nie pozwala Witoldowi wydostać się z jaskini.  Przy wejściu do portu zapada jeszcze raz decyzja o ostatniej próbie przy użyciu wielokrążka, który VVFF dostarcza helikopterem. Tym razem operacja udaje się. Dwóch grotołazów wraca do jaskini drogą morską razem z kilkoma VVFF. Tutaj zaopatrzeni w liny wydobywają ciało na powierzchnię za pomocą ręcznego kołowrotka. i przeciągają je do wyjścia za pomocą wielokrążka.</p>
<p>Była to jedna z najdłuższych i skomplikowanych interwencji , w których kiedykolwiek uczestniczyłem. Nie licząc morza nad którym nie mamy kontroli, problemy były przez cały czas powodowane przez fakt, że zostaliśmy wezwani z opóźnieniem przez VVFF i przez to musieliśmy pracować naprawdę na granicy ludzkiej wytrzymałości. Ciało zostało praktycznie wydobyte kawałek po kawałku. Kaptanat portu odpowiedzialny za operację nie ponosi dużej winy za opóźnienia, ponieważ nie wiedział w ogóle o istnieniu naszych nurków. Powinno to wpłynąć na sposób rozpowszechniania informacji o speleologii podwodnej i technikach stosowanych przez CNSAS. W Palinuro tego rodzaju wypadki zdarzają się co najmniej kilka razy w roku i są zawsze rozwiązywane przez nurków z VVFF dysponujących sprzętem i psychiką  niezbyt adekwatną do nurkowań jaskiniowych - co było też przyczyną samego wypadku.</p>
<p>Prawdopodobnie rozpowszechnienie w kapitanacie portu zasad naszej działalności dotyczących nurkowań jaskiniowych w strefie ryzyka (tak jak w Palinuro) mogłaby pozwolić uniknąć śmierci kilku nurków jaskiniowych, którzy mają ochotę awanturować się w podwodnych grotach.</p>
<p>Współpraca z VVFF była zawsze bardzo dobra - czego nie można powiedzieć o współpracy z prefekturą i Obroną Cywilną, której interwencja ograniczyła się tylko do pokrycia wydatków. Otrzymanych zresztą po wielu uciążliwych kontaktach telefonicznych. Natomiast komuna Centola była wspaniała i gościnna.</p>
<p>Wreszcie my : nurkowie CNSAS doskonali z punktu widzenia technicznego, rzuciliśmy się na problem naprawdę niezwykły. Główną trudność stanowił zaawansowany stan rozkładu ciała, co spowodowało pierwsze rozczłonkowanie trupa i było przyczyną różnych operacji, których można było uniknąć za pierwszym razem.</p>

<h3 align=right>Carlo Germani</h3>
<!--============================= CONTENTS END   ==========================================-->
<?php
	renderBottom($bSubdir);
?>